import type { ObservationTargetSummary } from "./targetTypes";
import type { FleetEvidence } from "./useFleetEvidence";
import { lastMetric } from "./useFleetEvidence";
import { capabilityLabels, formatAddress, type Destination } from "../../dashboardModel";
import { useState } from "react";
export function ServersPage({targets,evidence,cursor,nextCursor,setCursor,routeHref}: {
  targets: readonly ObservationTargetSummary[]; evidence: Readonly<Record<string,FleetEvidence>>;
  cursor?: string; nextCursor?: string; setCursor:(value:string|undefined)=>void;
  routeHref: (page: Destination, target: string) => string;
}) {
 const [search,setSearch]=useState(""); const [lifecycle,setLifecycle]=useState("");
 const visible=targets.filter(target => `${target.displayName} ${target.host}`.toLowerCase().includes(search.toLowerCase()) && (!lifecycle || target.lifecycle === lifecycle)).sort((a,b)=>a.displayName.localeCompare(b.displayName));
 return <><div className="kpi-grid">{[["Registered targets", targets.length], ["Active lifecycle", targets.filter(t => t.lifecycle === "active").length], ["Discovery pending", targets.filter(t => t.capabilityStatus === "pending").length], ["Visibility concerns", targets.filter(t => !["supported", "pending", "disabled", "retired"].includes(t.capabilityStatus)).length]].map(([label, value]) => <section className="kpi" key={label}><p>{label}</p><strong>{value}</strong><small>Loaded registration page only</small></section>)}</div>
        <div className="fleet-grid"><section className="panel"><header className="toolbar"><h2>Servers</h2><input aria-label="Search loaded servers" placeholder="Search loaded servers…" value={search} onChange={e => setSearch(e.target.value)}/><select aria-label="Lifecycle filter" value={lifecycle} onChange={e => setLifecycle(e.target.value)}><option value="">All lifecycles</option>{["active", "pending_discovery", "disabled", "retired"].map(value => <option key={value}>{value}</option>)}</select></header><div className="table-scroll"><table><caption>{visible.length} of {targets.length} loaded targets · sorted by name</caption><thead><tr><th scope="col">Server</th><th scope="col">Lifecycle</th><th scope="col">Capability discovery</th><th scope="col">Connections</th><th scope="col">SQL physical memory</th><th scope="col">Collection</th><th scope="col">Alerts</th></tr></thead><tbody>{visible.map(target => <tr key={target.instanceId}><td><a href={routeHref("health", target.instanceId)}>{target.displayName}</a><small>{formatAddress(target)}</small></td><td>{target.lifecycle.replaceAll("_", " ")}</td><td><span className={`capability-status status-${target.capabilityStatus}`}>{capabilityLabels[target.capabilityStatus]}</span></td><td>{lastMetric(evidence[target.instanceId]?.health, "engine.user_connections")}</td><td>{lastMetric(evidence[target.instanceId]?.health, "engine.process_physical_memory_bytes")}</td><td>{evidence[target.instanceId]?.health?.state ?? "Unavailable"}<small>{evidence[target.instanceId]?.loading ? "Refreshing…" : evidence[target.instanceId]?.health?.repositoryTimeUtc ?? "No health evidence"}</small>{evidence[target.instanceId]?.error ? <small role="status">{evidence[target.instanceId]?.error}. {evidence[target.instanceId]?.health ? "Showing last-known health." : "Refresh to retry."}</small> : null}</td><td><a href={routeHref("alerts", target.instanceId)}>{evidence[target.instanceId]?.alerts ? `${evidence[target.instanceId]?.alerts?.items.length} loaded${evidence[target.instanceId]?.alerts?.nextCursor ? "+" : ""}` : (evidence[target.instanceId]?.loading ? "Loading…" : "Alerts unavailable")}</a></td></tr>)}</tbody></table></div>{visible.length === 0 && <p className="empty-state">No servers match this loaded page.</p>}<footer className="toolbar"><span>Up to 50 targets per page · discovery is not collection health</span><button disabled={cursor === undefined} onClick={() => setCursor(undefined)}>First page</button><button disabled={!nextCursor} onClick={() => setCursor(nextCursor)}>Next page</button></footer></section>
        <section className="panel"><h2>Needs attention</h2><p>Up to 5 active alert records per loaded server. Collection gaps and discovery concerns are shown separately.</p>{targets.flatMap(target => (evidence[target.instanceId]?.alerts?.items ?? []).map(alert => <article className="attention-item" key={alert.alertId}><a href={routeHref("alerts", target.instanceId)}>{target.displayName} · {alert.state}</a><p>{alert.reason ?? "Alert evidence"}</p><small>{alert.firedUtc ?? alert.firstObservedUtc}</small></article>))}{targets.filter(target => evidence[target.instanceId]?.health && evidence[target.instanceId]?.health?.state !== "current").map(target => <article key={target.instanceId} className="attention-item"><a href={routeHref("health",target.instanceId)}>{target.displayName}</a><p>Collection: {evidence[target.instanceId]?.health?.state}</p></article>)}{targets.filter(t => !["supported", "disabled", "retired"].includes(t.capabilityStatus)).map(target => <article className="attention-item" key={target.instanceId}><a href={routeHref("health", target.instanceId)}>{target.displayName}</a><p>{capabilityLabels[target.capabilityStatus]}</p><details><summary>Discovery evidence</summary><ul>{target.capabilityReasons.map(reason => <li key={reason}>{reason}</li>)}</ul></details></article>)}<p className="muted">Select a server for collection freshness, activity and alert evidence.</p></section></div></>;
}
