<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>SqlObserver.IntegrationTests.PostgreSql</RootNamespace>
    <AssemblyName>SqlObserver.IntegrationTests.PostgreSql</AssemblyName>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <Reference Include="Microsoft.Extensions.Logging.Abstractions">
      <HintPath>$(NuGetPackageRoot)\microsoft.extensions.logging.abstractions\8.0.3\lib\net8.0\Microsoft.Extensions.Logging.Abstractions.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Content Include="$(NuGetPackageRoot)\microsoft.extensions.logging.abstractions\8.0.3\lib\net8.0\Microsoft.Extensions.Logging.Abstractions.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <ProjectReference Include="../../src/SqlObserver.Collector/SqlObserver.Collector.csproj" />
    <ProjectReference Include="../../src/SqlObserver.Collector.Abstractions/SqlObserver.Collector.Abstractions.csproj" />
    <ProjectReference Include="../../src/SqlObserver.Collectors/SqlObserver.Collectors.csproj" />
    <ProjectReference Include="../../src/SqlObserver.Infrastructure.PostgreSql/SqlObserver.Infrastructure.PostgreSql.csproj" />
    <ProjectReference Include="../../src/SqlObserver.Reporting/SqlObserver.Reporting.csproj" />
    <ProjectReference Include="../../src/SqlObserver.Observability/SqlObserver.Observability.csproj" />
    <ProjectReference Include="../../src/SqlObserver.Server/SqlObserver.Server.csproj" />
  </ItemGroup>
</Project>
