<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>SqlObserver.Infrastructure.Windows</RootNamespace>
    <AssemblyName>SqlObserver.Infrastructure.Windows</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../SqlObserver.Application/SqlObserver.Application.csproj" />
    <PackageReference Include="System.Diagnostics.EventLog" />
  </ItemGroup>
</Project>
