import assert from "node:assert/strict";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { buildRunbooks, LIMITS } from "../../tools/generate-m12-runbooks-evidence.mjs";

const root = path.resolve(import.meta.dirname, "../..");
const matrix = "8b87625c2a56ea07b1dfe826201557e54891341803a75f2a77d2296509f07aac";
const docs = ["m12-release-preflight", "m12-supply-chain-certification", "m12-candidate-evidence-verification", "m12-failed-run-quarantine-and-escalation"];
const sections = ["status", "scope", "supported-versions-and-environment", "prerequisites", "required-role", "blast-radius", "procedure", "verification", "failure-recovery", "evidence-and-utc-timestamps", "escalation-conditions", "explicit-exclusions"];
const cases = ["m12-sbom", "m12-licenses", "m12-vulnerability-scan", "m12-provenance"];
const options = (inputsPath, environment = "release-windows-server-2022") => ({ root, catalogPath: path.join(root, "release/certification/m12-runbooks-catalog.v1.json"), inputsPath, commitSha: "a".repeat(40), runId: "11111111-1111-4111-8111-111111111111", environmentId: environment, generatedAtUtc: "2026-08-28T00:00:00.0000000Z" });
function makeInputs(commitSha, environmentId, seed = "0") { return { $schema: "m12-runbooks-inputs.v1.schema.json", schemaVersion: 1, caseId: "m12-runbooks", commitSha, environmentId, matrixSha256: matrix, prerequisites: cases.map((caseId, index) => { const runId = `${seed.repeat(8)}-${String(index + 1).padStart(4, "0")}-4000-8000-000000000000`; const base = `TestResults/m12/${runId}`; const artifact = { "m12-sbom": "m12-sbom.cdx.json", "m12-licenses": "m12-licenses.json", "m12-vulnerability-scan": "m12-vulnerability-scan.json", "m12-provenance": "m12-provenance.json" }[caseId]; return { caseId, runId, path: base, artifactPath: `${base}/${artifact}`, testEvidencePath: `${base}/${caseId}-test-evidence.json`, provenancePath: `${base}/${caseId}-provenance.json`, artifactSha256: "c".repeat(64), artifactSize: 1, commitSha, environmentId }; }) }; }

test("runbook catalog is exact four documents and twelve sections", async () => { const catalog = JSON.parse(await readFile(path.join(root, "release/certification/m12-runbooks-catalog.v1.json"), "utf8")); assert.equal(catalog.documents.length, LIMITS.documents); for (const document of catalog.documents) { assert.ok(docs.includes(document.documentId)); assert.deepEqual(document.sectionIds, sections); const body = await readFile(path.join(root, document.path), "utf8"); assert.equal([...body.matchAll(/^## /gmu)].length, 12); } });
test("generator emits only bounded identities and is deterministic", async () => { const temp = await mkdtemp(path.join(root, ".m12-runbooks-test-")); try { const value = makeInputs("a".repeat(40), "release-windows-server-2022", "1"); const inputsPath = path.join(temp, "inputs.json"); await writeFile(inputsPath, `${JSON.stringify(value)}\n`); const one = await buildRunbooks(options(inputsPath)); const two = await buildRunbooks(options(inputsPath)); assert.deepEqual(one.bytes, two.bytes); assert.deepEqual(Object.keys(one.value), ["$schema", "schemaVersion", "caseId", "producerId", "kind", "result", "commitSha", "environmentId", "runId", "catalogSha256", "matrixSha256", "documents", "prerequisites"]); assert.deepEqual(Object.keys(one.value.documents[0]), ["documentId", "path", "sha256", "size", "sectionIds", "procedureIds"]); assert.deepEqual(Object.keys(one.value.prerequisites[0]), ["caseId", "runId"]); assert.ok(!one.bytes.toString("utf8").includes("# M12")); assert.equal(one.value.documents.length, 4); assert.equal(one.value.prerequisites.length, 4); } finally { await rm(temp, { recursive: true, force: true }); } });
test("generator rejects reordered, duplicate, forged, or nonfinal prerequisites", async () => { const temp = await mkdtemp(path.join(root, ".m12-runbooks-bad-")); try { const value = makeInputs("a".repeat(40), "release-windows-server-2022", "2"); const inputsPath = path.join(temp, "inputs.json"); value.prerequisites[1].caseId = "m12-sbom"; await writeFile(inputsPath, `${JSON.stringify(value)}\n`); await assert.rejects(() => buildRunbooks(options(inputsPath)), /prerequisite/); value.prerequisites[1].caseId = "m12-licenses"; value.prerequisites[0].path += "/raw"; await writeFile(inputsPath, `${JSON.stringify(value)}\n`); await assert.rejects(() => buildRunbooks(options(inputsPath)), /canonical/); } finally { await rm(temp, { recursive: true, force: true }); } });
test("generator rejects external inputs, unsafe paths, BOM/CRLF, and malformed UTC", async () => { const temp = await mkdtemp(path.join(root, ".m12-runbooks-adversarial-")); try { const value = makeInputs("b".repeat(40), "release-windows-server-2025", "3"); const inputsPath = path.join(temp, "inputs.json"); await writeFile(inputsPath, `${JSON.stringify(value)}\n`); await assert.rejects(() => buildRunbooks({ ...options(inputsPath, value.environmentId), generatedAtUtc: "2026-08-28T00:00:00Z" }), /UTC/); await writeFile(inputsPath, Buffer.concat([Buffer.from([0xef, 0xbb, 0xbf]), Buffer.from(`${JSON.stringify(value)}\n`)])); await assert.rejects(() => buildRunbooks(options(inputsPath, value.environmentId)), /BOM/); await writeFile(inputsPath, `${JSON.stringify(value)}\r\n`); await assert.rejects(() => buildRunbooks(options(inputsPath, value.environmentId)), /LF/); await assert.rejects(() => buildRunbooks({ ...options(path.join(temp, "outside.json"), value.environmentId) }), /escapes|missing/); } finally { await rm(temp, { recursive: true, force: true }); } });
test("generator rejects an unapproved matrix digest and unsafe exact heading", async () => { const temp = await mkdtemp(path.join(root, ".m12-runbooks-matrix-")); try { const value = makeInputs("d".repeat(40), "release-windows-server-2022", "4"); value.matrixSha256 = "f".repeat(64); const inputsPath = path.join(temp, "inputs.json"); await writeFile(inputsPath, `${JSON.stringify(value)}\n`); await assert.rejects(() => buildRunbooks(options(inputsPath)), /identity/); } finally { await rm(temp, { recursive: true, force: true }); } });
test("generator authority rejects unsafe deletion tokens and directory ADS suppression", async () => { const source = await readFile(path.join(root, "tools/generate-m12-runbooks-evidence.mjs"), "utf8"); assert.match(source, /\["rm ", "-rf"\]\.join\(""\)/u); assert.match(source, /\^### /u); assert.match(source, /-Stream \*/u); assert.doesNotMatch(source, /catch\{\$streams=@\(\)\}/u); });
