using SqlObserver.Application.Ports;
using SqlObserver.Domain.Collection;
using SqlObserver.Domain.Telemetry;
using System.Reflection;
using System.Text;
using System.Text.Json;

namespace SqlObserver.ApiContractTests;

public sealed class M7QueryPerformanceApiContractTests
{
    [Fact] public void AggregateMixedStateIsNotCoercedToPerDatabaseUnsupported() { var target = new MonitoredInstanceId(Guid.NewGuid()); var dto = new QueryPerformanceStatusDto(target, DateTimeOffset.UnixEpoch, QueryPerformanceSource.Mixed, "mixed", QueryCoverage.Truncated, false, true, false, "mixed_sources", []); Assert.Equal("mixed", dto.SourceState); Assert.NotEqual(QueryStoreState.Unsupported.ToString(), dto.SourceState); Assert.Throws<InvalidDataException>(() => QueryPerformanceAggregateState.Require("unexpected")); Assert.Throws<InvalidDataException>(() => new QueryPerformanceDatabaseStatusDto(5, "query_store_empty", "mixed", "query_store_empty", false, false, "none", 0, 0)); }
    [Fact] public void DatabaseCatalogPreservesNamesAndRejectsDuplicateIds() { var target = new MonitoredInstanceId(Guid.NewGuid()); var catalog = new[] { new QueryPerformanceDatabaseCatalogDto(5, "SqlObserverLabSales"), new QueryPerformanceDatabaseCatalogDto(7, "SqlObserverLabPublisher") }; var dto = new QueryPerformanceStatusDto(target, DateTimeOffset.UnixEpoch, QueryPerformanceSource.Mixed, "mixed", QueryCoverage.Complete, true, false, false, null, [], databaseCatalog: catalog); Assert.Equal("SqlObserverLabSales", dto.DatabaseCatalog[0].DatabaseName); Assert.Throws<InvalidDataException>(() => new QueryPerformanceStatusDto(target, DateTimeOffset.UnixEpoch, QueryPerformanceSource.Mixed, "mixed", QueryCoverage.Complete, true, false, false, null, [], databaseCatalog: [catalog[0], catalog[0]])); }
    [Fact] public void CursorBindsWindowMetricAndTarget() { var target = new MonitoredInstanceId(Guid.NewGuid()); var c = new QueryPerformanceCursorEnvelope(target,5,DateTimeOffset.UnixEpoch,DateTimeOffset.UnixEpoch.AddDays(1),QueryPerformanceMetric.CpuMilliseconds,DateTimeOffset.UtcNow,DateTimeOffset.UtcNow,new string('a',64)); Assert.Equal(target,c.TargetId); Assert.Equal(QueryPerformanceMetric.CpuMilliseconds,c.Metric); }
    [Fact] public void WindowIsLimitedToSevenDays() { Assert.Throws<ArgumentException>(() => new QueryPerformanceCursorEnvelope(new MonitoredInstanceId(Guid.NewGuid()),1,DateTimeOffset.UnixEpoch,DateTimeOffset.UnixEpoch.AddDays(8),QueryPerformanceMetric.CpuMilliseconds,DateTimeOffset.UtcNow,DateTimeOffset.UtcNow,new string('a',64))); }
    [Fact] public void PostgreSqlProjectionFirstPagesUseOneRepositoryClockSnapshotAndReplayCursorSnapshot() { string path = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "../../../../../src/SqlObserver.Infrastructure.PostgreSql/PostgreSqlQueryPerformanceApiProjectionPort.cs")); string source = File.ReadAllText(path); Assert.Contains("SELECT clock_timestamp();", source, StringComparison.Ordinal); Assert.Contains("request.Cursor?.SnapshotUtc ?? await ReadRepositorySnapshotAsync(c,s.Token)", source, StringComparison.Ordinal); Assert.DoesNotContain("request.Cursor?.SnapshotUtc??request.ToUtc", source, StringComparison.Ordinal); string migrationPath = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "../../../../../database/migrations/0011_query_performance.sql")); string migration = File.ReadAllText(migrationPath); Assert.Contains("r.committed_at<=p_snapshot_utc", migration, StringComparison.Ordinal); }
    [Fact] public void CursorDatabaseAndMetricBoundsAreStrict() { var target = new MonitoredInstanceId(Guid.NewGuid()); Assert.Throws<ArgumentOutOfRangeException>(() => new QueryPerformanceCursorEnvelope(target, 0, DateTimeOffset.UnixEpoch, DateTimeOffset.UnixEpoch.AddDays(1), QueryPerformanceMetric.CpuMilliseconds, DateTimeOffset.UtcNow, DateTimeOffset.UtcNow, new string('a',64), 1)); Assert.Throws<ArgumentOutOfRangeException>(() => new QueryPerformanceCursorEnvelope(target, 32768, DateTimeOffset.UnixEpoch, DateTimeOffset.UnixEpoch.AddDays(1), QueryPerformanceMetric.CpuMilliseconds, DateTimeOffset.UtcNow, DateTimeOffset.UtcNow, new string('a',64), 1)); }
    [Fact] public void CursorCarriesOpaqueObservationTie() { var c = new QueryPerformanceCursorEnvelope(new MonitoredInstanceId(Guid.NewGuid()),5,DateTimeOffset.UnixEpoch,DateTimeOffset.UnixEpoch.AddDays(1),QueryPerformanceMetric.CpuMilliseconds,DateTimeOffset.UtcNow,DateTimeOffset.UtcNow,new string('a',64),1,Guid.NewGuid(),new string('b',64),new string('c',32)); Assert.Equal(new string('c',32),c.ObservationKey); Assert.Throws<ArgumentException>(() => new QueryPerformanceCursorEnvelope(c.TargetId,5,c.FromUtc,c.ToUtc,c.Metric,c.SnapshotUtc,c.IntervalEndUtc,c.QueryFingerprint,1,c.CollectionRunId,c.PlanFingerprint,"bad")); }
    [Fact] public void ServerCursorDecoderRejectsMissingTieAndUnknownFields() { var target = Guid.NewGuid(); var from = DateTimeOffset.UnixEpoch; var to = from.AddDays(1); var run = Guid.NewGuid(); var complete = new Dictionary<string, object?> { ["targetId"] = target, ["databaseId"] = 5, ["fromUtc"] = from, ["toUtc"] = to, ["metric"] = 1, ["metricValue"] = 1, ["planFingerprint"] = null, ["observationKey"] = new string('c', 32), ["collectionRunId"] = run, ["snapshotUtc"] = from, ["intervalEndUtc"] = to, ["queryFingerprint"] = new string('a', 64) };
        var decoder = typeof(SqlObserver.Server.TargetQueryPerformanceApiEndpoints).GetMethod("DecodeCursor", BindingFlags.NonPublic | BindingFlags.Static)!;
        static string Encode(object value) => Convert.ToBase64String(JsonSerializer.SerializeToUtf8Bytes(value));
        object? Invoke(Dictionary<string, object?> value) => Assert.Throws<TargetInvocationException>(() => decoder.Invoke(null, [Encode(value), target, QueryPerformanceMetric.CpuMilliseconds, from, to, true]));
        var missing = new Dictionary<string, object?>(complete); missing.Remove("observationKey"); Invoke(missing);
        var extra = new Dictionary<string, object?>(complete) { ["unexpected"] = true }; Invoke(extra);
        var nullMetric = new Dictionary<string, object?>(complete) { ["metricValue"] = null }; Invoke(nullMetric);
        var zeroDb = new Dictionary<string, object?>(complete) { ["databaseId"] = 0 }; Invoke(zeroDb);
        var highDb = new Dictionary<string, object?>(complete) { ["databaseId"] = 32768 }; Invoke(highDb);
        Assert.Throws<TargetInvocationException>(() => decoder.Invoke(null, [new string('A', 2000), target, QueryPerformanceMetric.CpuMilliseconds, from, to, true]));
    }
    [Fact] public void HistoryCursorAllowsNullableCpuButTopCursorRejectsIt() { var target = new MonitoredInstanceId(Guid.NewGuid()); var from = DateTimeOffset.UnixEpoch; var to = from.AddDays(1); var c = new QueryPerformanceCursorEnvelope(target, 5, from, to, QueryPerformanceMetric.CpuMilliseconds, from, to, new string('a', 64), null, Guid.NewGuid(), null, new string('c', 32)); var encoder = typeof(SqlObserver.Server.TargetQueryPerformanceApiEndpoints).GetMethod("EncodeCursor", BindingFlags.NonPublic | BindingFlags.Static)!; var history = (string)encoder.Invoke(null, [c, false])!; Assert.NotEmpty(history); Assert.Throws<TargetInvocationException>(() => encoder.Invoke(null, [c, true])); }
    [Fact] public void TargetFailureStatusIsUnavailableAndNotFresh() { var dto = new QueryPerformanceStatusDto(new MonitoredInstanceId(Guid.NewGuid()), DateTimeOffset.UtcNow, QueryPerformanceSource.Unavailable, "unavailable", QueryCoverage.Unavailable, false, false, false, null, [], "deadline_exceeded", "deadline_exceeded"); Assert.Equal("unavailable", dto.SourceState); Assert.False(dto.Fresh); Assert.Throws<InvalidDataException>(() => new QueryPerformanceStatusDto(dto.TargetId, dto.SnapshotUtc, QueryPerformanceSource.QueryStore, "unsupported", QueryCoverage.Unavailable, true, false, false, null, [], "deadline_exceeded", "deadline_exceeded")); }
}
