-- Accept explicitly probed host metric capability flags.
SET LOCAL ROLE sqlobserver_migrator;
CREATE OR REPLACE FUNCTION control.update_m10_host_binding
 (p_instance_id uuid,p_host_id uuid,p_host_name text,p_identity_fingerprint bytea,p_expected_target_revision bigint,p_expected_binding_revision bigint,p_profile_revision bigint,p_profile jsonb,p_operation_id uuid,p_request_digest bytea,p_actor_sid text,p_correlation_id uuid,p_change_reason text)
RETURNS TABLE(operation_id uuid,state text,target_revision bigint,binding_revision bigint,repository_time timestamptz)
LANGUAGE plpgsql SECURITY DEFINER VOLATILE SET search_path=pg_catalog,control,audit AS $m10_bind$
DECLARE t control.observation_target%ROWTYPE; b control.host_binding%ROWTYPE; now_utc timestamptz:=clock_timestamp(); result_digest bytea; existing_request bytea; existing_result jsonb;
BEGIN
  IF coalesce(current_setting('sqlobserver.role',true),'') <> 'TargetAdministrator' OR coalesce(current_setting('sqlobserver.target_scope',true),'') IS DISTINCT FROM p_instance_id::text OR p_instance_id IS NULL OR p_host_id IS NULL OR p_operation_id IS NULL OR octet_length(p_request_digest)<>32 OR octet_length(p_identity_fingerprint)<>32 OR p_expected_target_revision<1 OR p_expected_binding_revision<0 OR p_profile_revision<1 OR p_host_name IS NULL OR octet_length(p_host_name) NOT BETWEEN 1 AND 512 OR p_profile IS NULL OR jsonb_typeof(p_profile)<>'object' OR octet_length(p_profile::text)>65536 OR (p_profile - 'osFamily' - 'osVersion' - 'cpuCount' - 'memoryBytes' - 'capabilityState' - 'capabilities')<>'{}'::jsonb OR coalesce(p_profile->>'osFamily','')='' OR length(p_profile->>'osFamily')>128 OR coalesce(p_profile->>'osVersion','')='' OR length(p_profile->>'osVersion')>128 OR (p_profile->>'cpuCount')::integer IS NULL OR (p_profile->>'cpuCount')::integer NOT BETWEEN 1 AND 65536 OR (p_profile->>'memoryBytes')::bigint IS NULL OR (p_profile->>'memoryBytes')::bigint NOT BETWEEN 0 AND 1152921504606846976 OR coalesce(p_profile->>'capabilityState','') NOT IN ('available','partial','unsupported','permission_denied') OR (p_profile ? 'capabilities' AND (jsonb_typeof(p_profile->'capabilities') IS DISTINCT FROM 'number' OR (p_profile->>'capabilities')::integer NOT BETWEEN 0 AND 15)) OR p_actor_sid IS NULL OR p_correlation_id IS NULL OR p_change_reason IS NULL OR length(p_change_reason) NOT BETWEEN 1 AND 512 THEN RAISE EXCEPTION 'host binding authorization or bounds rejected' USING ERRCODE='42501'; END IF;
 SELECT * INTO t FROM control.observation_target WHERE instance_id=p_instance_id FOR UPDATE;
 IF NOT FOUND OR t.revision<>p_expected_target_revision OR t.lifecycle_state NOT IN ('pending_discovery','active') THEN RAISE EXCEPTION 'host binding target revision conflict' USING ERRCODE='40001'; END IF;
 IF EXISTS(SELECT 1 FROM control.m10_mutation_replay r WHERE r.operation_id=p_operation_id) THEN SELECT r.request_digest,r.result INTO existing_request,existing_result FROM control.m10_mutation_replay r WHERE r.operation_id=p_operation_id; IF existing_request<>p_request_digest THEN RAISE EXCEPTION 'divergent host binding replay' USING ERRCODE='40001'; END IF; RETURN QUERY SELECT p_operation_id,'replayed',t.revision,(existing_result->>'bindingRevision')::bigint,now_utc; RETURN; END IF;
 SELECT * INTO b FROM control.host_binding WHERE instance_id=p_instance_id AND target_revision=t.revision FOR UPDATE;
 IF FOUND AND b.binding_revision<>p_expected_binding_revision THEN RAISE EXCEPTION 'host binding revision conflict' USING ERRCODE='40001'; END IF;
 IF NOT FOUND THEN INSERT INTO control.host_binding(instance_id,host_id,target_revision,binding_revision,host_name,identity_fingerprint,binding_state) VALUES(p_instance_id,p_host_id,t.revision,1,p_host_name,p_identity_fingerprint,'active') RETURNING * INTO b;
 ELSE UPDATE control.host_binding SET host_id=p_host_id,host_name=p_host_name,identity_fingerprint=p_identity_fingerprint,binding_revision=b.binding_revision+1,binding_state='active',last_seen_at=now_utc WHERE instance_id=p_instance_id AND target_revision=t.revision RETURNING * INTO b; END IF;
 IF p_profile_revision<>b.binding_revision THEN RAISE EXCEPTION 'host profile revision must equal binding revision' USING ERRCODE='22023'; END IF;
 INSERT INTO control.host_profile(instance_id,target_revision,host_id,binding_revision,profile_revision,os_family,os_version,cpu_count,memory_bytes,capability_state,profile)
 VALUES(p_instance_id,t.revision,p_host_id,b.binding_revision,p_profile_revision,p_profile->>'osFamily',p_profile->>'osVersion',(p_profile->>'cpuCount')::integer,(p_profile->>'memoryBytes')::bigint,p_profile->>'capabilityState',p_profile)
 ON CONFLICT(instance_id,target_revision,host_id,binding_revision,profile_revision) DO NOTHING;
 IF EXISTS (SELECT 1 FROM control.host_profile hp WHERE hp.instance_id=p_instance_id AND hp.target_revision=t.revision AND hp.host_id=p_host_id AND hp.binding_revision=b.binding_revision AND hp.profile_revision=p_profile_revision AND hp.profile IS DISTINCT FROM p_profile) THEN RAISE EXCEPTION 'divergent host profile revision' USING ERRCODE='40001'; END IF;
 result_digest:=sha256(convert_to(p_operation_id::text||'|'||b.binding_revision::text,'UTF8'));
 INSERT INTO control.m10_mutation_replay(operation_id,action_name,instance_id,request_digest,result_digest,result) VALUES(p_operation_id,'host_binding',p_instance_id,p_request_digest,result_digest,jsonb_build_object('bindingRevision',b.binding_revision,'targetRevision',t.revision));
 INSERT INTO audit.activity(occurred_at,activity_id,actor_kind,actor_identifier,action_name,authorization_result,outcome,subject_kind,subject_identifier,correlation_id,parameter_digest,safe_details) VALUES(now_utc,p_operation_id,'user',p_actor_sid,'host.binding.update','allowed','succeeded','observation_target',p_instance_id::text,p_correlation_id,p_request_digest,jsonb_build_object('changeReason',p_change_reason,'bindingRevision',b.binding_revision));
 RETURN QUERY SELECT p_operation_id,'committed',t.revision,b.binding_revision,now_utc;
END $m10_bind$;
