-- Confirmation windows gate pending episodes; a sustained active episode stays
-- confirmed until normal evidence resolves it. Match the pure evaluator.
SET LOCAL ROLE sqlobserver_migrator;
CREATE OR REPLACE FUNCTION alerting.evaluate_and_enqueue_internal(p_observations jsonb, p_decisions jsonb, p_work_key text, p_owner_execution_id uuid, p_lease_fencing bigint)
RETURNS TABLE(evaluated_count integer, changed_count integer, suppressed_count integer, completed_at timestamptz)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public, alerting, audit AS $$
DECLARE v_decision jsonb; v_observation jsonb; target uuid; rule uuid; observed timestamptz; next_state smallint; expected_state smallint; prior_state smallint; prior_operation uuid; prior_digest bytea; history_digest bytea; replay_result_digest bytea; replay_rule_revision bigint; replay_target_binding uuid; replay_rule_binding jsonb; computed_evidence bytea; operation uuid; evidence bytea; v_event_kind smallint; suppressed boolean; matches boolean; v_metric double precision; consecutive integer; expected_consecutive integer; expected_first timestamptz; prior_last_observed timestamptz; prior_first_match timestamptz; changed integer := 0; hidden integer := 0; n integer := 0; evaluated_operations uuid[] := ARRAY[]::uuid[]; now_utc timestamptz := clock_timestamp(); existing_alert uuid; next_alert uuid; existing_revision bigint; canonical_result jsonb; canonical_result_digest bytea; rule_config alerting.rule%ROWTYPE;
BEGIN
  IF p_lease_fencing IS NULL OR p_lease_fencing <= 0 OR jsonb_array_length(p_decisions) > 10000 OR jsonb_array_length(p_decisions) <> jsonb_array_length(p_observations) THEN RAISE EXCEPTION 'invalid alert evaluation lease or one-to-one batch'; END IF;
  IF (SELECT count(*) FROM jsonb_array_elements(p_decisions) d WHERE d->'Observation'->>'OperationId' IS NULL) > 0 OR (SELECT count(DISTINCT d->'Observation'->>'OperationId') FROM jsonb_array_elements(p_decisions) d) <> jsonb_array_length(p_decisions) THEN RAISE EXCEPTION 'alert operation identities must be unique'; END IF;
  IF (SELECT count(DISTINCT o->>'OperationId') FROM jsonb_array_elements(p_observations) o) <> jsonb_array_length(p_observations) OR EXISTS (SELECT 1 FROM jsonb_array_elements(p_decisions) d WHERE NOT EXISTS (SELECT 1 FROM jsonb_array_elements(p_observations) o WHERE o->>'OperationId'=d->'Observation'->>'OperationId' AND o->>'TargetId'=d->'Observation'->>'TargetId' AND o->>'RuleId'=d->'Observation'->>'RuleId' AND o->>'ObservedAtUtc'=d->'Observation'->>'ObservedAtUtc' AND coalesce(o->>'Value','')=coalesce(d->'Observation'->>'Value','') AND coalesce(o->>'CollectorHealthy','')=coalesce(d->'Observation'->>'CollectorHealthy','') AND coalesce(o->>'EvidenceDigest','')=coalesce(d->'Observation'->>'EvidenceDigest',''))) THEN RAISE EXCEPTION 'observation and decision bindings do not match'; END IF;
  FOR v_decision IN SELECT value FROM jsonb_array_elements(p_decisions) LOOP
    v_observation := v_decision->'Observation'; target := (v_observation->>'TargetId')::uuid; rule := (v_observation->>'RuleId')::uuid; observed := (v_observation->>'ObservedAtUtc')::timestamptz; next_state := (v_decision->'State'->>'State')::smallint; operation := (v_observation->>'OperationId')::uuid; evidence := decode(v_observation->>'EvidenceDigest','hex'); v_event_kind := NULLIF(v_decision->>'Event','')::smallint;
    IF jsonb_typeof(v_decision->'State') <> 'object' OR (SELECT count(*) FROM jsonb_object_keys(v_decision->'State')) <> 20 OR EXISTS (SELECT 1 FROM jsonb_object_keys(v_decision->'State') k WHERE k NOT IN ('RuleId','TargetId','State','ConsecutiveMatches','FirstMatchUtc','LastObservedUtc','FiredUtc','AcknowledgedUtc','ResolvedUtc','EpisodeStartedUtc','AlertId','EpisodeId','LastOperationId','EvidenceDigest','Reason','LastReason','DeliverySuppressed','AcknowledgedBy','Revision','LastValue')) THEN RAISE EXCEPTION 'alert decision state snapshot is malformed' USING ERRCODE='22023'; END IF;
    IF current_setting('sqlobserver.target_scope', true) IS NULL OR target::text <> current_setting('sqlobserver.target_scope', true) THEN RAISE EXCEPTION 'alert target scope mismatch' USING ERRCODE='42501'; END IF;
    IF operation IS NULL OR octet_length(evidence) <> 32 THEN RAISE EXCEPTION 'alert operation evidence is required' USING ERRCODE='22023'; END IF;
    IF operation IS DISTINCT FROM alerting.canonical_operation_id(target,rule,observed,v_observation->>'Reason') THEN RAISE EXCEPTION 'non-canonical alert operation identity' USING ERRCODE='22023'; END IF;
    computed_evidence := alerting.canonical_evidence_sha256(target,rule,v_observation->>'SourceKind',v_observation->>'MetricId',v_observation->>'SourceCollector',v_observation->>'SourceVersion',NULLIF(v_observation->>'SourceSchemaVersion','')::integer,v_observation->>'SourceDigest',observed,v_observation->>'SampleId',NULLIF(v_observation->>'RunId','')::uuid,NULLIF(v_observation->>'Value','')::double precision,NULLIF(v_observation->>'CollectorHealthy','')::boolean,v_observation->>'Reason');
    IF evidence IS DISTINCT FROM computed_evidence THEN RAISE EXCEPTION 'non-canonical alert evidence digest' USING ERRCODE='22023'; END IF;
    -- Check the independent replay ledger before touching rule state. Exact
    -- operation+digest replays return without mutation; divergent evidence is
    -- a conflict even when the current state has moved on.
    SELECT r.evidence_digest,r.result_digest,r.rule_revision,r.target_binding,r.rule_binding INTO history_digest,replay_result_digest,replay_rule_revision,replay_target_binding,replay_rule_binding FROM alerting.evaluation_replay r WHERE r.operation_id=operation AND r.instance_id=target AND r.rule_id=rule;
    IF FOUND THEN
      IF history_digest IS DISTINCT FROM evidence OR replay_result_digest IS DISTINCT FROM sha256(convert_to(alerting.canonical_decision_snapshot(v_decision)::text,'UTF8')) OR replay_target_binding IS DISTINCT FROM target OR replay_rule_revision IS DISTINCT FROM (SELECT r.revision FROM alerting.rule r WHERE r.instance_id=target AND r.rule_id=rule) OR replay_rule_binding IS DISTINCT FROM (SELECT to_jsonb(r) FROM alerting.rule r WHERE r.instance_id=target AND r.rule_id=rule) THEN RAISE EXCEPTION 'divergent alert replay' USING ERRCODE='40001'; END IF;
      CONTINUE;
    END IF;
    SELECT h.evidence_digest INTO history_digest FROM alerting.state_history h WHERE h.instance_id=target AND h.rule_id=rule AND h.operation_id=operation LIMIT 1;
    IF FOUND THEN
      IF history_digest IS DISTINCT FROM evidence OR EXISTS (SELECT 1 FROM alerting.rule_state s WHERE s.instance_id=target AND s.rule_id=rule AND (s.last_operation_id IS DISTINCT FROM operation OR s.state IS DISTINCT FROM next_state OR s.consecutive_matches IS DISTINCT FROM (v_decision->'State'->>'ConsecutiveMatches')::integer OR s.first_match_at IS DISTINCT FROM NULLIF(v_decision->'State'->>'FirstMatchUtc','')::timestamptz OR s.last_observed_at IS DISTINCT FROM NULLIF(v_decision->'State'->>'LastObservedUtc','')::timestamptz OR s.alert_id IS DISTINCT FROM NULLIF(v_decision->'State'->>'AlertId','')::uuid OR s.alert_episode_id IS DISTINCT FROM NULLIF(v_decision->'State'->>'EpisodeId','')::uuid OR s.resolved_at IS DISTINCT FROM NULLIF(v_decision->'State'->>'ResolvedUtc','')::timestamptz OR s.episode_started_at IS DISTINCT FROM NULLIF(v_decision->'State'->>'EpisodeStartedUtc','')::timestamptz OR s.acknowledged_by IS DISTINCT FROM v_decision->'State'->>'AcknowledgedBy' OR s.last_value IS DISTINCT FROM NULLIF(v_decision->'State'->>'LastValue','')::double precision OR s.reason IS DISTINCT FROM v_decision->'State'->>'Reason' OR s.last_reason IS DISTINCT FROM v_decision->'State'->>'LastReason' OR s.delivery_suppressed IS DISTINCT FROM (v_decision->'State'->>'DeliverySuppressed')::boolean OR s.revision IS DISTINCT FROM (v_decision->'State'->>'Revision')::bigint)) THEN RAISE EXCEPTION 'divergent alert history replay' USING ERRCODE='40001'; END IF;
      CONTINUE;
    END IF;
    SELECT r.* INTO rule_config FROM alerting.rule r WHERE r.instance_id=target AND r.rule_id=rule AND r.enabled;
    IF NOT FOUND OR (rule_config.kind=1 AND v_observation->>'Value' IS NULL) OR (rule_config.kind=2 AND v_observation->>'CollectorHealthy' IS NULL) THEN RAISE EXCEPTION 'alert observation rule binding is invalid' USING ERRCODE='22023'; END IF;
    IF rule_config.threshold IN ('NaN'::double precision,'Infinity'::double precision,'-Infinity'::double precision) OR rule_config.hysteresis IN ('NaN'::double precision,'Infinity'::double precision,'-Infinity'::double precision) OR rule_config.hysteresis < 0 OR rule_config.confirmation_count < 1 THEN RAISE EXCEPTION 'alert rule configuration is invalid' USING ERRCODE='22023'; END IF;
    SELECT s.state,s.last_operation_id,s.evidence_digest,s.alert_id,s.revision,s.last_observed_at,s.first_match_at INTO prior_state,prior_operation,prior_digest,existing_alert,existing_revision,prior_last_observed,prior_first_match FROM alerting.rule_state s WHERE s.instance_id=target AND s.rule_id=rule FOR UPDATE;
    consecutive := COALESCE((v_decision->'State'->>'ConsecutiveMatches')::integer,0);
    IF next_state NOT BETWEEN 1 AND 5 OR consecutive < 0 OR consecutive > rule_config.confirmation_count THEN RAISE EXCEPTION 'alert decision bounds are invalid' USING ERRCODE='22023'; END IF;
    v_metric := CASE WHEN rule_config.kind=2 THEN CASE WHEN lower(v_observation->>'CollectorHealthy')='true' THEN 1 ELSE 0 END ELSE NULLIF(v_observation->>'Value','')::double precision END;
    IF prior_last_observed IS NOT NULL AND observed < prior_last_observed THEN RAISE EXCEPTION 'alert observation time regressed' USING ERRCODE='22023'; END IF;
    IF rule_config.comparison=1 THEN matches := v_metric > (CASE WHEN prior_state IN (3,4) THEN rule_config.threshold-rule_config.hysteresis ELSE rule_config.threshold END);
    ELSIF rule_config.comparison=2 THEN matches := v_metric >= (CASE WHEN prior_state IN (3,4) THEN rule_config.threshold-rule_config.hysteresis ELSE rule_config.threshold END);
    ELSIF rule_config.comparison=3 THEN matches := v_metric < (CASE WHEN prior_state IN (3,4) THEN rule_config.threshold+rule_config.hysteresis ELSE rule_config.threshold END);
    ELSIF rule_config.comparison=4 THEN matches := v_metric <= (CASE WHEN prior_state IN (3,4) THEN rule_config.threshold+rule_config.hysteresis ELSE rule_config.threshold END);
    ELSE matches := abs(v_metric-rule_config.threshold) <= rule_config.hysteresis;
    END IF;
    expected_consecutive := CASE WHEN matches THEN LEAST(rule_config.confirmation_count,COALESCE((SELECT s.consecutive_matches FROM alerting.rule_state s WHERE s.instance_id=target AND s.rule_id=rule),0)+1) ELSE 0 END;
    expected_first := CASE WHEN matches THEN COALESCE(prior_first_match,observed) ELSE NULL END;
    IF matches AND coalesce(prior_state,1) NOT IN (3,4) AND expected_first IS NOT NULL AND observed-expected_first > rule_config.confirmation_window THEN expected_consecutive := 1; expected_first := observed; END IF;
    expected_state := CASE WHEN NOT matches THEN CASE WHEN prior_state IN (3,4) THEN 5 ELSE 1 END WHEN COALESCE(prior_state,1) IN (1,5) THEN CASE WHEN expected_consecutive >= rule_config.confirmation_count THEN 3 ELSE 2 END WHEN prior_state=2 THEN CASE WHEN expected_consecutive >= rule_config.confirmation_count THEN 3 ELSE 2 END ELSE COALESCE(prior_state,1) END;
    IF next_state IS DISTINCT FROM expected_state OR consecutive IS DISTINCT FROM expected_consecutive OR NULLIF(v_decision->'State'->>'FirstMatchUtc','')::timestamptz IS DISTINCT FROM expected_first THEN RAISE EXCEPTION 'alert decision state does not match repository evaluation' USING ERRCODE='22023'; END IF;
    IF v_event_kind IS DISTINCT FROM (CASE WHEN expected_state=3 AND COALESCE(prior_state,1) NOT IN (3,4) THEN 1 WHEN expected_state=5 AND prior_state IN (3,4) THEN 2 WHEN expected_state=4 AND prior_state=3 THEN 3 ELSE NULL END) THEN RAISE EXCEPTION 'alert event kind does not match legal transition' USING ERRCODE='22023'; END IF;
    IF next_state IN (3,4) AND NOT matches THEN RAISE EXCEPTION 'alert decision does not satisfy rule threshold' USING ERRCODE='22023'; END IF;
    IF next_state=3 AND consecutive < rule_config.confirmation_count THEN RAISE EXCEPTION 'alert firing confirmation is incomplete' USING ERRCODE='22023'; END IF;
    IF next_state=4 AND prior_state NOT IN (3,4) THEN RAISE EXCEPTION 'acknowledgement transition is illegal' USING ERRCODE='22023'; END IF;
    IF next_state=5 AND prior_state NOT IN (3,4) THEN RAISE EXCEPTION 'resolution transition is illegal' USING ERRCODE='22023'; END IF;
    IF next_state=1 AND COALESCE(prior_state,1) IN (3,4) THEN RAISE EXCEPTION 'illegal alert transition' USING ERRCODE='22023'; END IF;
    IF next_state=2 AND COALESCE(prior_state,1) NOT IN (1,2,5) THEN RAISE EXCEPTION 'illegal pending transition' USING ERRCODE='22023'; END IF;
    IF next_state=3 AND COALESCE(prior_state,1) NOT IN (1,2,3,5) THEN RAISE EXCEPTION 'illegal firing transition' USING ERRCODE='22023'; END IF;
    IF next_state=4 AND prior_state NOT IN (3,4) THEN RAISE EXCEPTION 'illegal acknowledgement transition' USING ERRCODE='22023'; END IF;
    IF next_state=5 AND prior_state NOT IN (3,4) THEN RAISE EXCEPTION 'illegal resolution transition' USING ERRCODE='22023'; END IF;
    IF prior_state IS NOT NULL AND existing_revision IS NULL THEN RAISE EXCEPTION 'alert state revision is required' USING ERRCODE='22023'; END IF;
    IF prior_operation = operation THEN
      IF prior_digest IS DISTINCT FROM evidence THEN RAISE EXCEPTION 'divergent alert replay' USING ERRCODE='40001'; END IF;
      CONTINUE;
    END IF;
    suppressed := alerting.maintenance_active_unscoped(target,observed);
    next_alert := CASE WHEN next_state IN (1,2) THEN NULL WHEN next_state=3 AND prior_state=5 THEN alerting.sha_uuid('alert|' || target::text || '|' || rule::text || '|' || operation::text) WHEN next_state IN (3,4) AND (prior_state IS DISTINCT FROM 3 AND prior_state IS DISTINCT FROM 4) AND existing_alert IS NULL THEN alerting.sha_uuid('alert|' || target::text || '|' || rule::text || '|' || operation::text) ELSE existing_alert END;
    IF COALESCE(v_decision->'State'->>'AlertId','') IS DISTINCT FROM COALESCE(next_alert::text,'') OR COALESCE(v_decision->'State'->>'EpisodeId','') IS DISTINCT FROM COALESCE((CASE WHEN next_state IN (1,2) THEN NULL WHEN next_state IN (3,4) AND (prior_state IS DISTINCT FROM 3 AND prior_state IS DISTINCT FROM 4) THEN operation ELSE (SELECT s.alert_episode_id FROM alerting.rule_state s WHERE s.instance_id=target AND s.rule_id=rule) END)::text,'') OR COALESCE(v_decision->'State'->>'LastOperationId','') IS DISTINCT FROM operation::text OR COALESCE(lower(v_decision->'State'->>'EvidenceDigest'),'') IS DISTINCT FROM encode(evidence,'hex') OR COALESCE((v_decision->'State'->>'DeliverySuppressed')::boolean,false) IS DISTINCT FROM suppressed OR (v_decision->'State'->>'State')::smallint IS DISTINCT FROM next_state OR (v_decision->'State'->>'ConsecutiveMatches')::integer IS DISTINCT FROM expected_consecutive OR NULLIF(v_decision->'State'->>'LastValue','')::double precision IS DISTINCT FROM NULLIF(v_observation->>'Value','')::double precision OR v_decision->'State'->>'Reason' IS DISTINCT FROM v_observation->>'Reason' OR v_decision->'State'->>'LastReason' IS DISTINCT FROM v_observation->>'Reason' THEN RAISE EXCEPTION 'alert decision state identity does not match repository evaluation' USING ERRCODE='22023'; END IF;
    INSERT INTO alerting.rule_state(instance_id,rule_id,alert_id,state,consecutive_matches,first_match_at,last_observed_at,fired_at,acknowledged_at,resolved_at,episode_started_at,acknowledged_by,last_value,reason,last_reason,delivery_suppressed,alert_episode_id,last_operation_id,evidence_digest,revision)
    VALUES(target,rule,next_alert,next_state,expected_consecutive,expected_first,observed,CASE WHEN prior_state=5 THEN CASE WHEN next_state=3 THEN observed ELSE NULL END WHEN next_state=3 THEN CASE WHEN prior_state=3 THEN (SELECT s.fired_at FROM alerting.rule_state s WHERE s.instance_id=target AND s.rule_id=rule) ELSE observed END ELSE CASE WHEN prior_state IN (3,4) THEN (SELECT s.fired_at FROM alerting.rule_state s WHERE s.instance_id=target AND s.rule_id=rule) ELSE NULL END END,CASE WHEN prior_state=5 THEN NULL WHEN next_state=4 THEN CASE WHEN prior_state=4 THEN (SELECT s.acknowledged_at FROM alerting.rule_state s WHERE s.instance_id=target AND s.rule_id=rule) ELSE observed END ELSE CASE WHEN prior_state=4 THEN (SELECT s.acknowledged_at FROM alerting.rule_state s WHERE s.instance_id=target AND s.rule_id=rule) ELSE NULL END END,CASE WHEN prior_state=5 THEN NULL WHEN next_state=5 THEN observed ELSE (SELECT s.resolved_at FROM alerting.rule_state s WHERE s.instance_id=target AND s.rule_id=rule) END,CASE WHEN next_state IN (1,2) THEN NULL WHEN next_state=3 AND prior_state=5 THEN observed WHEN next_state IN (3,4) AND (prior_state IS DISTINCT FROM 3 AND prior_state IS DISTINCT FROM 4) THEN observed ELSE (SELECT s.episode_started_at FROM alerting.rule_state s WHERE s.instance_id=target AND s.rule_id=rule) END,CASE WHEN prior_state=5 THEN NULL WHEN next_state=4 OR prior_state=4 THEN (SELECT s.acknowledged_by FROM alerting.rule_state s WHERE s.instance_id=target AND s.rule_id=rule) ELSE NULL END,(v_observation->>'Value')::double precision,v_observation->>'Reason',v_decision->'State'->>'LastReason',suppressed,CASE WHEN next_state IN (1,2) THEN NULL WHEN next_state=3 AND prior_state=5 THEN operation WHEN next_state IN (3,4) AND (prior_state IS DISTINCT FROM 3 AND prior_state IS DISTINCT FROM 4) THEN operation ELSE (SELECT s.alert_episode_id FROM alerting.rule_state s WHERE s.instance_id=target AND s.rule_id=rule) END,operation,evidence,coalesce(existing_revision,1)+1)
    ON CONFLICT(instance_id,rule_id) DO UPDATE SET alert_id=EXCLUDED.alert_id,state=EXCLUDED.state,consecutive_matches=EXCLUDED.consecutive_matches,first_match_at=EXCLUDED.first_match_at,last_observed_at=EXCLUDED.last_observed_at,fired_at=EXCLUDED.fired_at,acknowledged_at=EXCLUDED.acknowledged_at,resolved_at=EXCLUDED.resolved_at,episode_started_at=EXCLUDED.episode_started_at,acknowledged_by=EXCLUDED.acknowledged_by,last_value=EXCLUDED.last_value,reason=EXCLUDED.reason,last_reason=EXCLUDED.last_reason,delivery_suppressed=EXCLUDED.delivery_suppressed,alert_episode_id=EXCLUDED.alert_episode_id,last_operation_id=EXCLUDED.last_operation_id,evidence_digest=EXCLUDED.evidence_digest,revision=alerting.rule_state.revision+1;
    -- Reconstruct the complete result from the validated SQL row.  The
    -- caller's JSON is only an input assertion; it is never persisted.
    SELECT jsonb_build_object(
      'Observation', jsonb_build_object(
        'TargetId', target, 'RuleId', rule, 'ObservedAtUtc', observed,
        'Value', NULLIF(v_observation->>'Value','')::double precision,
        'CollectorHealthy', NULLIF(v_observation->>'CollectorHealthy','')::boolean,
        'Reason', v_observation->>'Reason', 'SampleId', v_observation->>'SampleId',
        'RunId', NULLIF(v_observation->>'RunId','')::uuid,
        'SourceKind', v_observation->>'SourceKind', 'MetricId', v_observation->>'MetricId',
        'SourceCollector', v_observation->>'SourceCollector', 'SourceVersion', v_observation->>'SourceVersion',
        'SourceSchemaVersion', NULLIF(v_observation->>'SourceSchemaVersion','')::integer,
        'SourceDigest', v_observation->>'SourceDigest', 'OperationId', operation,
        'EvidenceDigest', encode(evidence,'hex')),
      'State', jsonb_build_object(
        'RuleId', s.rule_id, 'TargetId', s.instance_id, 'State', s.state,
        'ConsecutiveMatches', s.consecutive_matches, 'FirstMatchUtc', s.first_match_at,
        'LastObservedUtc', s.last_observed_at, 'FiredUtc', s.fired_at,
        'AcknowledgedUtc', s.acknowledged_at, 'ResolvedUtc', s.resolved_at,
        'EpisodeStartedUtc', s.episode_started_at, 'AlertId', s.alert_id,
        'EpisodeId', s.alert_episode_id, 'LastOperationId', s.last_operation_id,
        'EvidenceDigest', encode(s.evidence_digest,'hex'), 'Reason', s.reason,
        'LastReason', s.last_reason, 'DeliverySuppressed', s.delivery_suppressed,
        'AcknowledgedBy', s.acknowledged_by, 'Revision', s.revision, 'LastValue', s.last_value),
      'Event', v_event_kind, 'DeliverySuppressed', s.delivery_suppressed, 'Reason', CASE WHEN s.delivery_suppressed THEN 'maintenance' ELSE 'evaluated' END)
      INTO canonical_result
      FROM alerting.rule_state s WHERE s.instance_id=target AND s.rule_id=rule;
    canonical_result_digest := sha256(convert_to(canonical_result::text,'UTF8'));
    IF alerting.canonical_decision_snapshot(v_decision) IS DISTINCT FROM canonical_result THEN
      RAISE EXCEPTION 'alert decision snapshot does not match server state' USING ERRCODE='22023';
    END IF;
    IF EXISTS (SELECT 1 FROM alerting.state_history h WHERE h.instance_id=target AND h.rule_id=rule AND h.operation_id=operation AND (h.evidence_digest IS DISTINCT FROM evidence OR h.result_digest IS DISTINCT FROM canonical_result_digest)) THEN RAISE EXCEPTION 'divergent alert history payload' USING ERRCODE='40001'; END IF;
    INSERT INTO alerting.state_history(instance_id,rule_id,alert_id,from_state,to_state,observed_at,reason,delivery_suppressed,operation_id,evidence_digest,result_digest) SELECT target,rule,s.alert_id,prior_state,next_state,observed,s.reason,s.delivery_suppressed,operation,evidence,canonical_result_digest FROM alerting.rule_state s WHERE s.instance_id=target AND s.rule_id=rule;
    INSERT INTO alerting.evaluation_replay(operation_id,instance_id,rule_id,rule_revision,target_binding,rule_binding,evidence_digest,result_digest,result) VALUES(operation,target,rule,rule_config.revision,target,to_jsonb(rule_config),evidence,canonical_result_digest,canonical_result) ON CONFLICT(operation_id) DO NOTHING;
    n := n + 1; evaluated_operations := array_append(evaluated_operations, operation); IF prior_state IS DISTINCT FROM next_state THEN changed := changed + 1; END IF; IF suppressed THEN hidden := hidden + 1; END IF;
    IF v_event_kind IS NOT NULL THEN INSERT INTO alerting.delivery_outbox(delivery_id,alert_id,instance_id,rule_id,destination_id,event_kind,payload,due_at,operation_id,evidence_digest,destination_revision,destination_kind,destination_configuration_reference,destination_approval_revision,destination_approval_digest,destination_approval_scope,destination_configuration_digest) SELECT gen_random_uuid(),s.alert_id,target,rule,x.destination_id,v_event_kind,jsonb_build_object('schemaVersion',1,'operationId',operation,'evidenceDigest',encode(evidence,'hex'),'alertId',s.alert_id,'ruleId',rule,'targetId',target,'event',v_event_kind,'reasonCode',v_decision->>'Reason','suppressed',suppressed),CASE WHEN suppressed THEN COALESCE((SELECT max(m.ends_at) FROM alerting.maintenance_window m WHERE m.instance_id=target AND m.cancelled_at IS NULL AND observed>=m.starts_at AND observed<m.ends_at),now_utc) ELSE now_utc END,operation,evidence,x.revision,x.kind,x.configuration_reference,x.approved_revision,x.approval_digest,x.approval_scope,x.configuration_digest FROM alerting.rule_state s JOIN alerting.destination x ON x.instance_id=target AND x.enabled AND x.approved AND x.approval_scope=target AND x.approved_kind=x.kind AND x.approved_configuration_reference=x.configuration_reference AND x.approved_revision IS NOT NULL AND x.approval_digest IS NOT NULL AND x.instance_id=target WHERE s.instance_id=target AND s.rule_id=rule ON CONFLICT(alert_id,destination_id,event_kind) DO NOTHING; END IF;
  END LOOP;
  UPDATE alerting.evaluation_queue q SET completed_at=now_utc,claimed_until=NULL,claim_work_key=NULL,claim_owner_execution_id=NULL,claim_fencing=NULL,next_due_at=now_utc+r.evaluation_interval,due_at=now_utc+r.evaluation_interval
  FROM alerting.rule r
  WHERE r.rule_id=q.rule_id AND r.instance_id=q.instance_id
    AND q.completed_at IS NULL AND q.claimed_until>now_utc
    AND q.claim_work_key=p_work_key AND q.claim_owner_execution_id=p_owner_execution_id AND q.claim_fencing=p_lease_fencing
    AND q.operation_id=ANY(evaluated_operations)
    AND EXISTS (SELECT 1 FROM jsonb_array_elements(p_decisions) decision WHERE (decision->'Observation'->>'OperationId')::uuid=q.operation_id AND (decision->'Observation'->>'TargetId')::uuid=q.instance_id AND (decision->'Observation'->>'RuleId')::uuid=q.rule_id AND (decision->'Observation'->>'ObservedAtUtc')::timestamptz=q.observed_at AND decode(decision->'Observation'->>'EvidenceDigest','hex')=q.evidence_digest);
  INSERT INTO audit.activity(occurred_at,activity_id,actor_kind,actor_identifier,action_name,authorization_result,outcome,subject_kind,subject_identifier,correlation_id,safe_details) VALUES(now_utc,gen_random_uuid(),'service','collector','alerting.evaluate','allowed','succeeded','alert_evaluation',p_lease_fencing::text,gen_random_uuid(),jsonb_build_object('evaluated_count',n,'changed_count',changed));
  RETURN QUERY SELECT n,changed,hidden,now_utc;
END $$;
