-- Keep the local generated job identity distinct from the conflict-target column.
-- This preserves the existing backfill authorization, revision and replay fences.
SET LOCAL ROLE sqlobserver_migrator;
SET LOCAL lock_timeout = '5s';
CREATE OR REPLACE FUNCTION control.enqueue_m10_backfill
 (p_instance_id uuid,p_from_utc timestamptz,p_to_utc timestamptz,p_metric_key text,p_expected_target_revision bigint,p_operation_id uuid,p_request_digest bytea,p_actor_sid text,p_correlation_id uuid,p_change_reason text)
RETURNS TABLE(operation_id uuid,state text,target_revision bigint,job_count integer,repository_time timestamptz)
LANGUAGE plpgsql SECURITY DEFINER VOLATILE SET search_path=pg_catalog,control,audit AS $m10_backfill_enqueue$
DECLARE t control.observation_target%ROWTYPE; d date; n integer:=0; now_utc timestamptz:=clock_timestamp(); v_job_id uuid; result_digest bytea; existing_request bytea; existing_result jsonb;
BEGIN
  IF coalesce(current_setting('sqlobserver.role',true),'') <> 'TargetAdministrator' OR coalesce(current_setting('sqlobserver.target_scope',true),'') IS DISTINCT FROM p_instance_id::text OR p_instance_id IS NULL OR p_operation_id IS NULL OR octet_length(p_request_digest)<>32 OR p_expected_target_revision<1 OR p_from_utc IS NULL OR p_to_utc IS NULL OR p_from_utc>=p_to_utc OR extract(timezone from p_from_utc)<>0 OR extract(timezone from p_to_utc)<>0 OR p_to_utc-p_from_utc>interval '90 days' OR p_metric_key IS NOT NULL AND (length(p_metric_key)>128 OR p_metric_key !~ '^[a-z][a-z0-9._-]*$') OR p_actor_sid IS NULL OR p_correlation_id IS NULL OR p_change_reason IS NULL OR length(p_change_reason) NOT BETWEEN 1 AND 512 THEN RAISE EXCEPTION 'backfill authorization or bounds rejected' USING ERRCODE='42501'; END IF;
 SELECT * INTO t FROM control.observation_target WHERE instance_id=p_instance_id FOR SHARE;
 IF NOT FOUND OR t.revision<>p_expected_target_revision THEN RAISE EXCEPTION 'backfill target revision conflict' USING ERRCODE='40001'; END IF;
 IF EXISTS(SELECT 1 FROM control.m10_mutation_replay r WHERE r.operation_id=p_operation_id) THEN SELECT r.request_digest,r.result INTO existing_request,existing_result FROM control.m10_mutation_replay r WHERE r.operation_id=p_operation_id; IF existing_request<>p_request_digest THEN RAISE EXCEPTION 'divergent backfill replay' USING ERRCODE='40001'; END IF; RETURN QUERY SELECT p_operation_id,'replayed',t.revision,coalesce((existing_result->>'jobCount')::integer,0),now_utc; RETURN; END IF;
 d:=p_from_utc::date; WHILE d::timestamptz<p_to_utc LOOP v_job_id:=left(encode(sha256(convert_to('m10-backfill|'||p_operation_id::text||'|'||d::text,'UTF8')),'hex'),32)::uuid; INSERT INTO control.analytics_job(job_id,job_kind,instance_id,target_revision,from_utc,to_utc,metric_key,cursor,status,work_key,owner_execution_id,fencing_token) VALUES(v_job_id,'backfill',p_instance_id,t.revision,greatest(p_from_utc,d::timestamptz),least(p_to_utc,(d+1)::timestamptz),p_metric_key,NULL,'queued','analytics/backfill',p_operation_id,1) ON CONFLICT(job_id) DO NOTHING; n:=n+1; d:=d+1; END LOOP;
 result_digest:=sha256(convert_to(p_operation_id::text||'|'||n::text,'UTF8')); INSERT INTO control.m10_mutation_replay(operation_id,action_name,instance_id,request_digest,result_digest,result) VALUES(p_operation_id,'analytics_backfill',p_instance_id,p_request_digest,result_digest,jsonb_build_object('jobCount',n,'targetRevision',t.revision)); INSERT INTO audit.activity(occurred_at,activity_id,actor_kind,actor_identifier,action_name,authorization_result,outcome,subject_kind,subject_identifier,correlation_id,parameter_digest,safe_details) VALUES(now_utc,p_operation_id,'user',p_actor_sid,'analytics.backfill.enqueue','allowed','succeeded','observation_target',p_instance_id::text,p_correlation_id,p_request_digest,jsonb_build_object('fromUtc',p_from_utc,'toUtc',p_to_utc,'jobCount',n,'changeReason',p_change_reason)); RETURN QUERY SELECT p_operation_id,'queued',t.revision,n,now_utc;
END $m10_backfill_enqueue$;
REVOKE ALL ON FUNCTION control.enqueue_m10_backfill(uuid,timestamptz,timestamptz,text,bigint,uuid,bytea,text,uuid,text) FROM PUBLIC,sqlobserver_collector,sqlobserver_auditor;
GRANT EXECUTE ON FUNCTION control.enqueue_m10_backfill(uuid,timestamptz,timestamptz,text,bigint,uuid,bytea,text,uuid,text) TO sqlobserver_server;
