using SqlObserver.Application.Ports;
using SqlObserver.Domain.Authorization;
using SqlObserver.Domain.Collection;
using SqlObserver.Domain.Targets;
using SqlObserver.Domain.Telemetry;

namespace SqlObserver.Application.Services;

public sealed class QueryPerformanceApiQueryService : IQueryPerformanceApiQueryService
{
    private static readonly ApplicationRole[] ReadRoles = [ApplicationRole.Viewer, ApplicationRole.Operator, ApplicationRole.TargetAdministrator];
    private readonly IQueryPerformanceApiRepositoryPort repository;
    public QueryPerformanceApiQueryService(IQueryPerformanceApiRepositoryPort repository) => this.repository = repository ?? throw new ArgumentNullException(nameof(repository));
    public ValueTask<QueryPerformanceStatusDto?> GetStatusAsync(AuthorizationContext authorization, QueryPerformanceStatusRequest request, CancellationToken cancellationToken) { Authorize(authorization, request.TargetId); ValidateWindow(request.FromUtc, request.ToUtc); return repository.GetStatusAsync(request, cancellationToken); }
    public async ValueTask<TopQueryPage> GetTopAsync(AuthorizationContext authorization, TopQueryRequest request, CancellationToken cancellationToken) { Authorize(authorization, request.TargetId); ValidateWindow(request.FromUtc, request.ToUtc); if (request.Limit is <= 0 or > 200 || !Enum.IsDefined(request.Metric)) throw new ArgumentOutOfRangeException(nameof(request)); if (request.Cursor is not null && (request.Cursor.MetricValue is null || request.Cursor.CollectionRunId is null || request.Cursor.ObservationKey is null)) throw new InvalidDataException("Top query cursor tie keys are incomplete."); TopQueryPage page = await repository.GetTopAsync(request, cancellationToken); if (page.Items.Count > request.Limit || page.HasMore && page.Items.Count != request.Limit || page.SnapshotUtc.Offset != TimeSpan.Zero || page.Items.Any(x => x.TargetId != request.TargetId || x.ContentAvailable || x.Query.DatabaseId is <= 0 or > 32767 || x.Metric != request.Metric || x.Value is null || !ConcreteSourceMatrix(x.Source, x.SourceState, x.Semantics) || x.IntervalStartUtc < request.FromUtc || x.IntervalEndUtc > request.ToUtc || x.IntervalEndUtc <= x.IntervalStartUtc || x.IntervalEndUtc-x.IntervalStartUtc > TimeSpan.FromDays(7))) throw new InvalidDataException("Top query projection exceeded its bounds."); return page with { NextCursor = page.HasMore && page.Items.Count > 0 ? Cursor(page.Items[^1], request, page.SnapshotUtc) : null }; }
    public async ValueTask<QueryHistoryPage> GetHistoryAsync(AuthorizationContext authorization, QueryHistoryRequest request, CancellationToken cancellationToken) { Authorize(authorization, request.TargetId); ValidateWindow(request.FromUtc, request.ToUtc); if (request.Limit is <= 0 or > 200) throw new ArgumentOutOfRangeException(nameof(request)); QueryHistoryPage page = await repository.GetHistoryAsync(request, cancellationToken); if (page.Items.Count > request.Limit || page.HasMore && page.Items.Count != request.Limit || page.SnapshotUtc.Offset != TimeSpan.Zero || page.Items.Any(x => x.TargetId != request.TargetId || x.Query.DatabaseId is <= 0 or > 32767 || x.Query.QueryFingerprint != request.Query.QueryFingerprint || x.ContentAvailable || !ConcreteSourceMatrix(x.Source, x.SourceState, x.Semantics) || x.IntervalStartUtc < request.FromUtc || x.IntervalEndUtc > request.ToUtc || x.IntervalEndUtc <= x.IntervalStartUtc)) throw new InvalidDataException("Query history projection exceeded its bounds."); return page with { NextCursor = page.HasMore && page.Items.Count > 0 ? Cursor(page.Items[^1], request, page.SnapshotUtc) : null }; }
    public async ValueTask<QueryPlanMetadataDto?> GetPlanAsync(AuthorizationContext authorization, QueryPlanMetadataRequest request, CancellationToken cancellationToken) { Authorize(authorization, request.TargetId); var row = await repository.GetPlanAsync(request, cancellationToken); if (row is not null && (row.TargetId != request.TargetId || row.ContentAvailable)) throw new InvalidDataException("Plan projection exceeded its contract."); return row; }
    private static void Authorize(AuthorizationContext a, MonitoredInstanceId target) { ArgumentNullException.ThrowIfNull(a); if (!ReadRoles.Any(a.HasRole) || !a.CanAccess(target)) throw new UnauthorizedAccessException("The caller is not authorized for this observation target."); }
    private static void ValidateWindow(DateTimeOffset from, DateTimeOffset to) { if (from.Offset != TimeSpan.Zero || to.Offset != TimeSpan.Zero || to <= from || to-from > TimeSpan.FromDays(7)) throw new ArgumentException("UTC window must be increasing and at most seven days."); }
    private static bool ConcreteSourceMatrix(QueryPerformanceSource source, QueryStoreState state, QueryMetricSemantics semantics) => source switch { QueryPerformanceSource.QueryStore => semantics == QueryMetricSemantics.QueryStoreInterval && state is QueryStoreState.ReadWrite or QueryStoreState.ReadOnly, QueryPerformanceSource.PlanCache => semantics != QueryMetricSemantics.QueryStoreInterval && state is QueryStoreState.ReadFailure or QueryStoreState.PermissionDenied or QueryStoreState.TimedOut or QueryStoreState.Unsupported, _ => false };
    private static QueryPerformanceCursorEnvelope Cursor(TopQueryDto item, TopQueryRequest request, DateTimeOffset snapshot) => item.CollectionRunId is null || item.ObservationKey is null ? throw new InvalidDataException("Top query continuation tie keys are incomplete.") : new(item.TargetId, item.Query.DatabaseId, request.FromUtc, request.ToUtc, request.Metric, snapshot, item.IntervalEndUtc, item.Query.QueryFingerprint, item.Value, item.CollectionRunId, item.Plan?.PlanFingerprint, item.ObservationKey);
    private static QueryPerformanceCursorEnvelope Cursor(QueryHistoryDto item, QueryHistoryRequest request, DateTimeOffset snapshot) => item.CollectionRunId is null || item.ObservationKey is null ? throw new InvalidDataException("Query history continuation tie keys are incomplete.") : new(item.TargetId, item.Query.DatabaseId, request.FromUtc, request.ToUtc, QueryPerformanceMetric.CpuMilliseconds, snapshot, item.IntervalEndUtc, item.Query.QueryFingerprint, item.Metrics.CpuMilliseconds, item.CollectionRunId, item.PlanFingerprint, item.ObservationKey);
}
