<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>SqlObserver.Server</RootNamespace>
    <AssemblyName>SqlObserver.Server</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Negotiate" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" />
    <ProjectReference Include="../SqlObserver.Alerting/SqlObserver.Alerting.csproj" />
    <ProjectReference Include="../SqlObserver.Analytics/SqlObserver.Analytics.csproj" />
    <ProjectReference Include="../SqlObserver.Application/SqlObserver.Application.csproj" />
    <ProjectReference Include="../SqlObserver.Audit/SqlObserver.Audit.csproj" />
    <ProjectReference Include="../SqlObserver.Infrastructure.PostgreSql/SqlObserver.Infrastructure.PostgreSql.csproj" />
    <ProjectReference Include="../SqlObserver.Infrastructure.Windows/SqlObserver.Infrastructure.Windows.csproj" />
    <ProjectReference Include="../SqlObserver.Mcp/SqlObserver.Mcp.csproj" />
    <ProjectReference Include="../SqlObserver.Security/SqlObserver.Security.csproj" />
    <ProjectReference Include="../SqlObserver.Reporting/SqlObserver.Reporting.csproj" />
  </ItemGroup>
</Project>
