using System.Text;
using SqlObserver.Reporting;
using SqlObserver.Domain.Authorization;
using SqlObserver.Domain.Auditing;

namespace SqlObserver.UnitTests;

public sealed class M12ReportContractTests
{
    private static readonly string[] ExpectedKinds = ["instance-health", "performance-window", "incident-evidence", "capacity-readiness"];
    [Fact] public void CatalogContainsExactlyFourVersionedReports() => Assert.Equal(ExpectedKinds, ReportCatalog.All.Select(x => x.ReportKind));
    [Fact] public void ReportsAllowOnlyTargetScopedOperationalRoles() { Guid target = Guid.NewGuid(); foreach (ApplicationRole role in new[] { ApplicationRole.Viewer, ApplicationRole.Operator, ApplicationRole.TargetAdministrator }) Assert.True(ReportAuthorization.CanAccess(target, new AuthorizationContext(new ActorSecurityIdentifier("S-1-5-21-1"), AuthorizationPrincipalState.Active, [new RoleAuthorizationGrant(role, TargetAuthorizationScope.ForTargets([new SqlObserver.Domain.Telemetry.MonitoredInstanceId(target)]))]))); foreach (ApplicationRole role in new[] { ApplicationRole.SecurityAdministrator, ApplicationRole.Auditor, ApplicationRole.CollectorService }) Assert.False(ReportAuthorization.CanAccess(target, new AuthorizationContext(new ActorSecurityIdentifier("S-1-5-21-1"), AuthorizationPrincipalState.Active, [new RoleAuthorizationGrant(role, TargetAuthorizationScope.ForTargets([new SqlObserver.Domain.Telemetry.MonitoredInstanceId(target)]))]))); }

    [Fact] public void HealthRejectsWindows() => Assert.Throws<ArgumentException>(() => ReportRequestValidation.Validate(new ReportCreateRequest(Guid.NewGuid(), new ReportRequest("instance-health", Guid.NewGuid(), DateTimeOffset.UtcNow.AddHours(-1), DateTimeOffset.UtcNow), TestAuthorization())));

    [Fact] public void DigestOmitsOperationId() { ReportRequest a = new("performance-window", Guid.NewGuid(), Utc(-1), Utc(0)); ReportRequest b = a with { OperationId = Guid.NewGuid() }; Assert.Equal(ReportRequestValidation.CanonicalDigest(a), ReportRequestValidation.CanonicalDigest(b)); }

    [Fact] public void CsvNeutralizesFormulaAndControls() { ReportDefinition definition = ReportCatalog.Get(ReportKind.InstanceHealth); byte[] bytes = ReportRenderer.RenderCsv(definition, definition.Sections[0], [new ReportRow(1, new Dictionary<string, string?> { ["metric"] = "=SUM(A1)", ["value"] = "a\r\nb" })]); string csv = Encoding.UTF8.GetString(bytes); Assert.Contains("'=SUM(A1)", csv); Assert.DoesNotContain("\r\n\r\n", csv); }
    [Fact] public void CsvNeutralizesFormulaAfterContractWhitespace() { ReportDefinition definition = ReportCatalog.Get(ReportKind.InstanceHealth); byte[] bytes = ReportRenderer.RenderCsv(definition, definition.Sections[0], [new ReportRow(1, new Dictionary<string, string?> { ["metric"] = " \t\u00a0=SUM(A1)", ["value"] = "safe" })]); string csv = Encoding.UTF8.GetString(bytes); Assert.Contains(" \t\u00a0'=SUM(A1)", csv); }

    [Fact] public void HtmlEncodesUntrustedValues() { ReportDefinition definition = ReportCatalog.Get(ReportKind.InstanceHealth); var run = new ReportRun(Guid.NewGuid(), Guid.NewGuid(), 1, ReportKind.InstanceHealth, 1, DateTimeOffset.UtcNow, DateTimeOffset.UtcNow.AddHours(24), "", "finalized"); byte[] bytes = ReportRenderer.RenderHtml(run, definition, new Dictionary<string, IReadOnlyList<ReportRow>> { ["health"] = [new ReportRow(1, new Dictionary<string, string?> { ["metric"] = "<script>alert(1)</script>" })] }); Assert.DoesNotContain("<script>", Encoding.UTF8.GetString(bytes)); }

    [Fact] public async Task UnauthorizedCreateAuditsBeforeRepositoryIo() { var repo = new FakeRepository(); var audit = new FakeAudit(); var service = new ReportService(repo, audit); await Assert.ThrowsAsync<UnauthorizedAccessException>(() => service.CreateAsync(new ReportCreateRequest(Guid.NewGuid(), new ReportRequest("instance-health", Guid.NewGuid()), Authorization(false)), CancellationToken.None).AsTask()); Assert.Equal(0, repo.CreateCalls); Assert.Contains("deny", audit.Kinds); }
    [Fact] public async Task AuditFailureFailsClosedAfterRepositoryRead() { var repo = new FakeRepository(); var audit = new FakeAudit { Throw = true }; var service = new ReportService(repo, audit); await Assert.ThrowsAsync<ReportAuditException>(() => service.GetRunAsync(Guid.NewGuid(), Guid.NewGuid(), Authorization(true), CancellationToken.None).AsTask()); Assert.Equal(1, repo.ReadCalls); }
    [Fact] public async Task ExportReadsAllBoundedPagesBeforeDisclosure() { var repo = new PagingRepository(); var audit = new FakeAudit(); var service = new ReportService(repo, audit); Guid target = Guid.NewGuid(), run = Guid.NewGuid(); IReadOnlyList<ReportRow> rows = await service.ReadAllAsync(target, run, "health", 500, 1_000_000, Authorization(true), CancellationToken.None); Assert.Equal(250, rows.Count); Assert.Equal(2, repo.PageCalls); Assert.Contains("read", audit.Kinds); await service.CompleteExportAsync(target, run, "health", "csv", rows.Count, Authorization(true), CancellationToken.None); Assert.Contains("export", audit.Kinds); }
    [Fact] public async Task OversizePageIsAuditedAndRejected() { var audit = new FakeAudit(); var service = new ReportService(new FakeRepository(), audit); await Assert.ThrowsAsync<ReportLimitException>(() => service.ReadPageAsync(Guid.NewGuid(), Guid.NewGuid(), "health", 0, 201, Authorization(true), CancellationToken.None).AsTask()); Assert.Contains("oversize", audit.Kinds); }
    [Fact] public async Task ClientCancellationIsNotMisreportedAsServerTimeout() { using var cancellation = new CancellationTokenSource(); cancellation.Cancel(); var service = new ReportService(new CancellationRepository(), new FakeAudit()); await Assert.ThrowsAnyAsync<OperationCanceledException>(() => service.ReadAllAsync(Guid.NewGuid(), Guid.NewGuid(), "health", 200, 1_000_000, Authorization(true), cancellation.Token).AsTask()); }
    [Fact] public void CursorUsesTimeLimitedProtectionAndAllBindings() { string root = FindRoot(); string source = File.ReadAllText(Path.Combine(root, "src/SqlObserver.Reporting/ReportRendering.cs")); Assert.Contains("ToTimeLimitedDataProtector", source, StringComparison.Ordinal); foreach (string field in new[] { "TargetRevision", "DefinitionVersion", "Section", "AfterOrdinal", "SnapshotUtc", "ExpiresAtUtc" }) Assert.Contains(field, source, StringComparison.Ordinal); }

    private static DateTimeOffset Utc(int hours) => new DateTimeOffset(2026, 8, 26, 12, 0, 0, TimeSpan.Zero).AddHours(hours);
    private static string FindRoot() { string path = AppContext.BaseDirectory; while (!File.Exists(Path.Combine(path, "SqlObserver.slnx"))) path = Directory.GetParent(path)?.FullName ?? throw new DirectoryNotFoundException(); return path; }
    private static SqlObserver.Domain.Authorization.AuthorizationContext TestAuthorization() => new(new SqlObserver.Domain.Auditing.ActorSecurityIdentifier("S-1-5-21-1"), SqlObserver.Domain.Authorization.AuthorizationPrincipalState.Active, [new SqlObserver.Domain.Authorization.RoleAuthorizationGrant(SqlObserver.Domain.Authorization.ApplicationRole.Viewer, SqlObserver.Domain.Authorization.TargetAuthorizationScope.ForAllTargets())]);
    private static AuthorizationContext Authorization(bool allowed) => new(new ActorSecurityIdentifier("S-1-5-21-2"), AuthorizationPrincipalState.Active, [new RoleAuthorizationGrant(ApplicationRole.Viewer, allowed ? TargetAuthorizationScope.ForAllTargets() : TargetAuthorizationScope.None())]);
    private sealed class FakeRepository : IReportRepository { public int CreateCalls; public int ReadCalls; public ValueTask<ReportRun> CreateAsync(Guid t, ReportRequest r, string a, CancellationToken c) { CreateCalls++; return ValueTask.FromResult(new ReportRun(Guid.NewGuid(), t, 1, r.ParsedKind, 1, Utc(0), Utc(24), "", "finalized")); } public ValueTask<ReportRun?> GetRunAsync(Guid t, Guid r, CancellationToken c) { ReadCalls++; return ValueTask.FromResult<ReportRun?>(new ReportRun(r, t, 1, ReportKind.InstanceHealth, 1, Utc(0), Utc(24), "", "finalized")); } public ValueTask<ReportSectionPage> ReadPageAsync(Guid t, Guid r, string s, long a, int l, CancellationToken c) => ValueTask.FromResult(new ReportSectionPage(new ReportRun(r, t, 1, ReportKind.InstanceHealth, 1, Utc(0), Utc(24), "", "finalized"), s, [], null, false)); }
    private sealed class PagingRepository : IReportRepository { public int PageCalls; public ValueTask<ReportRun> CreateAsync(Guid t, ReportRequest r, string a, CancellationToken c) => throw new NotSupportedException(); public ValueTask<ReportRun?> GetRunAsync(Guid t, Guid r, CancellationToken c) => ValueTask.FromResult<ReportRun?>(new ReportRun(r, t, 1, ReportKind.InstanceHealth, 1, Utc(0), Utc(24), "", "finalized")); public ValueTask<ReportSectionPage> ReadPageAsync(Guid t, Guid r, string s, long a, int l, CancellationToken c) { PageCalls++; int count = PageCalls == 1 ? 200 : 50; long start = a + 1; IReadOnlyList<ReportRow> rows = Enumerable.Range(0, count).Select(i => new ReportRow(start + i, new Dictionary<string, string?> { ["metric"] = "m" })).ToArray(); return ValueTask.FromResult(new ReportSectionPage(new ReportRun(r, t, 1, ReportKind.InstanceHealth, 1, Utc(0), Utc(24), "", "finalized"), s, rows, PageCalls == 1 ? "200" : null, PageCalls == 1)); } }
    private sealed class CancellationRepository : IReportRepository { public ValueTask<ReportRun> CreateAsync(Guid t, ReportRequest r, string a, CancellationToken c) => throw new NotSupportedException(); public ValueTask<ReportRun?> GetRunAsync(Guid t, Guid r, CancellationToken c) => throw new OperationCanceledException(c); public ValueTask<ReportSectionPage> ReadPageAsync(Guid t, Guid r, string s, long a, int l, CancellationToken c) => throw new OperationCanceledException(c); }
    private sealed class FakeAudit : IReportAuditPort { public bool Throw; public List<string> Kinds { get; } = []; public ValueTask AppendAsync(ReportAuditEvent e, CancellationToken c) { Kinds.Add(e.ActivityKind); return Throw ? ValueTask.FromException(new InvalidOperationException()) : ValueTask.CompletedTask; } }
}
