<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>SqlObserver.UnitTests</RootNamespace>
    <AssemblyName>SqlObserver.UnitTests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/SqlObserver.Alerting/SqlObserver.Alerting.csproj" />
    <ProjectReference Include="../../src/SqlObserver.Audit/SqlObserver.Audit.csproj" />
    <ProjectReference Include="../../src/SqlObserver.Application/SqlObserver.Application.csproj" />
    <ProjectReference Include="../../src/SqlObserver.Collector.Abstractions/SqlObserver.Collector.Abstractions.csproj" />
    <ProjectReference Include="../../src/SqlObserver.Collectors/SqlObserver.Collectors.csproj" />
    <ProjectReference Include="../../src/SqlObserver.Domain/SqlObserver.Domain.csproj" />
    <ProjectReference Include="../../src/SqlObserver.Infrastructure.Windows/SqlObserver.Infrastructure.Windows.csproj" />
    <ProjectReference Include="../../src/SqlObserver.Infrastructure.SqlServer/SqlObserver.Infrastructure.SqlServer.csproj" />
    <ProjectReference Include="../../src/SqlObserver.Infrastructure.PostgreSql/SqlObserver.Infrastructure.PostgreSql.csproj" />
    <ProjectReference Include="../../src/SqlObserver.Analytics/SqlObserver.Analytics.csproj" />
    <ProjectReference Include="../../src/SqlObserver.Collector/SqlObserver.Collector.csproj" />
    <ProjectReference Include="../../src/SqlObserver.Reporting/SqlObserver.Reporting.csproj" />
  </ItemGroup>
</Project>
