<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>SqlObserver.Collectors</RootNamespace>
    <AssemblyName>SqlObserver.Collectors</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../SqlObserver.Collector.Abstractions/SqlObserver.Collector.Abstractions.csproj" />
    <ProjectReference Include="../SqlObserver.Domain/SqlObserver.Domain.csproj" />
  </ItemGroup>
</Project>
