const MAX_BYTES = 1024 * 1024;
const MAX_ITEMS = 256;
const MAX_CURSOR = 512;
const LOCK_MODES = new Set(["NL", "S", "U", "X", "IS", "IU", "IX", "SIU", "SIX", "UIX", "SCH_S", "SCH_M", "BU", "RANGES_S", "RANGES_U", "RANGEI_N", "RANGEI_S", "RANGEX_X", "OTHER"]);
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;
const UTC = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,7})?Z$/;
export function normalizeDeadlockLockMode(value) { const token = typeof value === "string" ? value.trim().toUpperCase().replaceAll("-", "_") : ""; return token.length <= 32 && LOCK_MODES.has(token) ? token : "OTHER"; }
export function parseDeadlockPage(input, expectedTargetId) {
  const text = typeof input === "string" ? input : JSON.stringify(input);
  if (new TextEncoder().encode(text).byteLength > MAX_BYTES) throw new Error("Deadlock response exceeds the bounded limit.");
  const value = typeof input === "string" ? JSON.parse(input) : input;
  if (!value || typeof value !== "object" || typeof value.targetId !== "string" || !UUID.test(value.targetId) || expectedTargetId !== undefined && value.targetId !== expectedTargetId || !Array.isArray(value.items) || value.items.length > MAX_ITEMS || typeof value.repositoryTimeUtc !== "string" || !UTC.test(value.repositoryTimeUtc)) throw new Error("Deadlock response is invalid.");
  const items = value.items.map((item) => { if (!item || typeof item !== "object" || typeof item.eventId !== "string" || !UUID.test(item.eventId) || typeof item.fingerprint !== "string" || !/^[0-9a-f]{64}$/.test(item.fingerprint) || typeof item.occurredAtUtc !== "string" || !UTC.test(item.occurredAtUtc) || !Number.isInteger(item.participantCount) || item.participantCount < 0 || item.participantCount > 128 || !Number.isInteger(item.relationCount) || item.relationCount < 0 || item.relationCount > 256 || typeof item.parseTruncated !== "boolean" || typeof item.collectedAtUtc !== "string" || !UTC.test(item.collectedAtUtc)) throw new Error("Deadlock item is invalid."); return { eventId: item.eventId, occurredAtUtc: item.occurredAtUtc, fingerprint: item.fingerprint, participantCount: item.participantCount, relationCount: item.relationCount, parseTruncated: item.parseTruncated, collectedAtUtc: item.collectedAtUtc }; });
  if (value.nextCursor !== undefined && value.nextCursor !== null && (typeof value.nextCursor !== "string" || value.nextCursor.length === 0 || value.nextCursor.length > MAX_CURSOR)) throw new Error("Deadlock cursor is invalid.");
  return { targetId: value.targetId, repositoryTimeUtc: value.repositoryTimeUtc, items, nextCursor: value.nextCursor ?? undefined };
}
export function parseDeadlockDetail(input, expectedTargetId, expectedEventId) { const value = typeof input === "string" ? JSON.parse(input) : input; if (!value || typeof value !== "object" || !value.summary) throw new Error("Deadlock detail is invalid."); const page = parseDeadlockPage({ targetId: expectedTargetId, repositoryTimeUtc: value.summary.collectedAtUtc, items: [value.summary] }, expectedTargetId); if (page.items[0].eventId !== expectedEventId) throw new Error("Deadlock detail identity is invalid."); if (!Array.isArray(value.participants) || value.participants.length !== page.items[0].participantCount || value.participants.length > 128 || value.participants.some((item) => !Number.isInteger(item.sessionId) || item.sessionId < 1 || item.sessionId > 32767 || typeof item.isVictim !== "boolean")) throw new Error("Deadlock participants are invalid."); if (!Array.isArray(value.relations) || value.relations.length !== page.items[0].relationCount || value.relations.length > 256 || value.relations.some((item) => !Number.isInteger(item.blockerSessionId) || !Number.isInteger(item.waiterSessionId) || item.blockerSessionId < 1 || item.blockerSessionId > 32767 || item.waiterSessionId < 1 || item.waiterSessionId > 32767 || !["key", "page", "object_lock", "metadata", "exchange", "other"].includes(item.resourceCategory) || normalizeDeadlockLockMode(item.lockMode) !== item.lockMode)) throw new Error("Deadlock relations are invalid."); return { summary: page.items[0], participants: value.participants, relations: value.relations }; }
