import { responseFailure } from "../../api/responseFailure.ts";
import { readBoundedBody } from "../activity/activityParser.mjs";
import type { QueryPerformanceDatabaseCatalog, QueryPerformanceDatabaseStatus, QueryPerformanceFilters, QueryPerformanceHistoryPage, QueryPerformanceItem, QueryPerformanceMetric, QueryPerformancePage, QueryPerformancePlan, QueryPerformanceStatus } from "./queryPerformanceTypes";

const maximumResponseBytes = 8 * 1024 * 1024;
const states = new Set(["read_write", "read_only", "disabled", "unsupported", "permission_denied", "read_failure", "timed_out", "mixed", "unavailable"]);
const semantics = new Set(["query_store_interval", "plan_cache_cumulative", "plan_cache_delta", "plan_cache_baseline", "reset"]);
const coverage = new Set(["complete", "truncated", "unavailable", "no_activity"]);
const sources = new Set(["query_store", "plan_cache", "mixed", "unavailable"]);
const databaseStatuses = new Set(["query_store_empty", "query_store_rows", "query_store_disabled", "query_store_unsupported", "query_store_permission_denied", "query_store_read_failure", "query_store_timed_out", "plan_cache_rows", "plan_cache_empty", "plan_cache_permission_denied", "plan_cache_read_failure", "plan_cache_timed_out", "output_capped"]);
const lossKinds = new Set(["none", "source_row_limit", "response_byte_limit", "output_validation_failure", "ingestion_rejection", "duplicate_overlap"]);
const statusReasons = new Set(["query_store_empty", "query_store_read", "query_store_disabled", "query_store_unsupported", "query_store_probe_missing", "query_store_permission_denied", "query_store_read_failure", "query_store_timeout", "plan_cache_fallback", "plan_cache_empty", "plan_cache_permission_denied", "plan_cache_read_failure", "plan_cache_timeout", "output_capped"]);
const metrics = new Set(["cpu", "duration", "executions", "logical_reads", "writes", "rows"]);
function statusReasonCompatible(status: string, reason: string): boolean {
  return status === "query_store_empty" && reason === "query_store_empty" || status === "query_store_rows" && (reason === "query_store_read" || reason === "query_store_empty") || status === "query_store_disabled" && reason === "query_store_disabled" || status === "query_store_unsupported" && (reason === "query_store_unsupported" || reason === "query_store_probe_missing") || status === "query_store_permission_denied" && reason === "query_store_permission_denied" || status === "query_store_read_failure" && reason === "query_store_read_failure" || status === "query_store_timed_out" && reason === "query_store_timeout" || status === "plan_cache_rows" && reason === "plan_cache_fallback" || status === "plan_cache_empty" && reason === "plan_cache_empty" || status === "plan_cache_permission_denied" && reason === "plan_cache_permission_denied" || status === "plan_cache_read_failure" && reason === "plan_cache_read_failure" || status === "plan_cache_timed_out" && reason === "plan_cache_timeout" || status === "output_capped" && reason === "output_capped";
}
const digest = (value: unknown): value is string => typeof value === "string" && /^[0-9a-f]{64}$/iu.test(value);
const optionalDigest = (value: unknown): value is string | null | undefined => value === null || value === undefined || digest(value);
const timestamp = (value: unknown): value is string => typeof value === "string" && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,7})?Z$/u.test(value) && !Number.isNaN(Date.parse(value));
const canonicalInstant = (value: string): string => value.replace(/(?:\.(\d{1,7}))?Z$/u, (_match, fraction: string | undefined) => `.${(fraction ?? "").padEnd(7, "0")}Z`);
const metric = (value: unknown): value is number | null | undefined => value === undefined || value === null || typeof value === "number" && Number.isSafeInteger(value) && value >= 0;

async function readJson(url: string, expectedTargetId: string, signal?: AbortSignal): Promise<unknown> {
  const response = await fetch(url, { signal, headers: { Accept: "application/json" } });
  if (!response.ok) throw responseFailure(response, response.status === 404 ? "Query performance evidence is unavailable." : "Query performance request failed.");
  if (!/^application\/json(?:;|$)/iu.test(response.headers.get("content-type") ?? "")) throw new Error("Query performance response content type was invalid.");
  const length = Number(response.headers.get("content-length") ?? "0");
  if (!Number.isFinite(length) || length > maximumResponseBytes) throw new Error("Query performance response exceeded its bound.");
  let body: string; try { body = await readBoundedBody(response, signal ?? new AbortController().signal, maximumResponseBytes); } catch { throw new Error("Query performance response exceeded its bound."); }
  let value: unknown; try { value = JSON.parse(body); } catch { throw new Error("Query performance response was invalid."); }
  if (typeof value !== "object" || value === null || (value as { targetId?: unknown }).targetId !== expectedTargetId) throw new Error("Query performance response was outside its target contract.");
  return value;
}
function item(value: unknown, metric: QueryPerformanceMetric = "cpu"): QueryPerformanceItem {
  if (typeof value !== "object" || value === null) throw new Error("Query performance item was invalid."); const i = value as Record<string, unknown>; const v = i.value;
  const source = String(i.source); const sourceState = String(i.sourceState); const semantic = String(i.semantics); const sourceMatrix = source === "query_store" && semantic === "query_store_interval" && (sourceState === "read_write" || sourceState === "read_only") || source === "plan_cache" && semantic !== "query_store_interval" && (sourceState === "disabled" || sourceState === "read_failure" || sourceState === "permission_denied" || sourceState === "timed_out" || sourceState === "unsupported");
  if (typeof i.databaseId !== "number" || !Number.isInteger(i.databaseId) || i.databaseId <= 0 || i.databaseId > 32767 || !digest(i.queryFingerprint) || !optionalDigest(i.planFingerprint) || !sources.has(source) || source === "mixed" || source === "unavailable" || sourceState === "mixed" || sourceState === "unavailable" || !states.has(sourceState) || typeof i.metric !== "string" || i.metric !== metric || !semantics.has(semantic) || !sourceMatrix || typeof v !== "number" && v !== null || typeof v === "number" && (!Number.isSafeInteger(v) || v < 0) || !timestamp(i.intervalStartUtc) || !timestamp(i.intervalEndUtc) || Date.parse(String(i.intervalEndUtc)) <= Date.parse(String(i.intervalStartUtc)) || !coverage.has(String(i.coverage)) || typeof i.fresh !== "boolean" || typeof i.truncated !== "boolean" || i.contentAvailable !== false || typeof i.collectionRunId !== "string" || !/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu.test(i.collectionRunId) || typeof i.observationKey !== "string" || !/^[0-9a-f]{32}$/iu.test(i.observationKey)) throw new Error("Query performance item was outside its bounds.");
  const metricKey = { cpu: "cpuMilliseconds", duration: "durationMilliseconds", executions: "executions", logical_reads: "logicalReads", writes: "writes", rows: "rows" }[metric];
  return { query: { databaseId: i.databaseId, queryFingerprint: i.queryFingerprint }, plan: typeof i.planFingerprint === "string" ? { planFingerprint: i.planFingerprint } : undefined, source: i.source as QueryPerformanceItem["source"], sourceState: String(i.sourceState), semantics: String(i.semantics), metrics: { [metricKey]: v as number | null }, intervalStartUtc: i.intervalStartUtc, intervalEndUtc: i.intervalEndUtc, coverage: String(i.coverage), fresh: i.fresh, truncated: i.truncated, contentAvailable: false, collectionRunId: i.collectionRunId, observationKey: i.observationKey };
}
export async function getQueryPerformanceTop(instanceId: string, metric: QueryPerformanceMetric, cursor?: string, fromUtc?: string, toUtc?: string, signal?: AbortSignal, filters: QueryPerformanceFilters = {}): Promise<QueryPerformancePage> {
  if (filters.databaseId !== undefined && (!Number.isInteger(filters.databaseId) || filters.databaseId <= 0 || filters.databaseId > 32767) || filters.source !== undefined && filters.source !== "query_store" && filters.source !== "plan_cache") throw new Error("Query performance filters were invalid.");
  if (!metrics.has(metric) || fromUtc !== undefined && (toUtc === undefined || !timestamp(fromUtc) || !timestamp(toUtc) || Date.parse(toUtc) <= Date.parse(fromUtc) || Date.parse(toUtc) - Date.parse(fromUtc) > 7 * 24 * 60 * 60 * 1000)) throw new Error("Query performance top request bounds were invalid.");
  if (cursor !== undefined && (cursor.length === 0 || cursor.length > 1024)) throw new Error("Query performance cursor exceeded its bound.");
  if (cursor !== undefined && (fromUtc === undefined || toUtc === undefined)) throw new Error("Query performance cursor requires its bound window.");
  const windowQuery = fromUtc === undefined || toUtc === undefined ? "" : `&fromUtc=${encodeURIComponent(fromUtc)}&toUtc=${encodeURIComponent(toUtc)}`;
  const cursorQuery = cursor === undefined ? "" : `&cursor=${encodeURIComponent(cursor)}`;
  const filterQuery = `${filters.databaseId === undefined ? "" : `&databaseId=${filters.databaseId}`}${filters.source === undefined ? "" : `&source=${filters.source}`}`;
  const value = await readJson(`/api/v1/observation-targets/${encodeURIComponent(instanceId)}/query-performance/top?metric=${metric}&limit=200${windowQuery}${cursorQuery}${filterQuery}`, instanceId, signal) as { metric?: unknown; items?: unknown; snapshotUtc?: unknown; nextCursor?: unknown; fromUtc?: unknown; toUtc?: unknown };
  if (value.metric !== metric || !timestamp(value.snapshotUtc) || !Array.isArray(value.items) || value.items.length > 200 || value.nextCursor !== undefined && value.nextCursor !== null && (typeof value.nextCursor !== "string" || value.nextCursor.length === 0 || value.nextCursor.length > 1024) || typeof value.fromUtc !== "string" || typeof value.toUtc !== "string" || !timestamp(value.fromUtc) || !timestamp(value.toUtc) || fromUtc !== undefined && canonicalInstant(value.fromUtc) !== canonicalInstant(fromUtc) || toUtc !== undefined && canonicalInstant(value.toUtc) !== canonicalInstant(toUtc)) throw new Error("Query performance top response was outside its bounds.");
  const effectiveFrom = value.fromUtc; const effectiveTo = value.toUtc;
  const items = value.items.map(x => { const parsed = item(x, metric); if (filters.databaseId !== undefined && parsed.query.databaseId !== filters.databaseId || filters.source !== undefined && parsed.source !== filters.source) throw new Error("Query performance item was outside its filter scope."); if (effectiveFrom !== undefined && effectiveTo !== undefined && (Date.parse(parsed.intervalStartUtc) < Date.parse(effectiveFrom) || Date.parse(parsed.intervalEndUtc) > Date.parse(effectiveTo))) throw new Error("Query performance top item was outside its bound window."); return parsed; }); return { repositoryTimeUtc: value.snapshotUtc, items, nextCursor: typeof value.nextCursor === "string" ? value.nextCursor : undefined, fromUtc: effectiveFrom, toUtc: effectiveTo };
}
export async function getQueryPerformance(instanceId: string, signal?: AbortSignal): Promise<QueryPerformancePage> {
  const metrics: QueryPerformanceMetric[] = ["cpu", "duration", "executions", "logical_reads", "writes", "rows"]; const to = new Date().toISOString(); const from = new Date(Date.parse(to) - 24 * 60 * 60 * 1000).toISOString(); const pages = await Promise.all(metrics.map(metric => getQueryPerformanceTop(instanceId, metric, undefined, from, to, signal))); const merged = new Map<string, QueryPerformanceItem>();
  const firstPage = pages[0]; if (firstPage === undefined) throw new Error("Query performance returned no metric pages.");
  if (pages.some(page => page.repositoryTimeUtc !== firstPage.repositoryTimeUtc || page.fromUtc !== firstPage.fromUtc || page.toUtc !== firstPage.toUtc)) throw new Error("Query performance metric pages did not share one repository snapshot and window.");
  pages.forEach(page => page.items.forEach(x => { const key = `${x.collectionRunId}:${x.observationKey}`; const prior = merged.get(key); merged.set(key, prior === undefined ? x : { ...prior, metrics: { ...prior.metrics, ...x.metrics } }); }));
  const cursorsByMetric: Partial<Record<QueryPerformanceMetric, string>> = {}; pages.forEach((page, index) => { const metricName = metrics[index]; if (metricName !== undefined && page.nextCursor !== undefined) cursorsByMetric[metricName] = page.nextCursor; });
  return { repositoryTimeUtc: firstPage.repositoryTimeUtc, items: [...merged.values()], nextCursor: firstPage.nextCursor, cursorsByMetric, fromUtc: firstPage.fromUtc, toUtc: firstPage.toUtc };
}
export async function getQueryPerformanceStatus(instanceId: string, fromUtc?: string, toUtc?: string, signal?: AbortSignal): Promise<QueryPerformanceStatus> {
  if (fromUtc !== undefined && (toUtc === undefined || !timestamp(fromUtc) || !timestamp(toUtc) || Date.parse(toUtc) <= Date.parse(fromUtc) || Date.parse(toUtc) - Date.parse(fromUtc) > 7 * 24 * 60 * 60 * 1000)) throw new Error("Query performance status window was invalid.");
  const query = fromUtc === undefined || toUtc === undefined ? "" : `?fromUtc=${encodeURIComponent(fromUtc)}&toUtc=${encodeURIComponent(toUtc)}`;
  const value = await readJson(`/api/v1/observation-targets/${encodeURIComponent(instanceId)}/query-performance/status${query}`, instanceId, signal) as Record<string, unknown>; const raw = value.databaseStatuses; const rawCatalog = value.databaseCatalog;
  const targetStatuses = new Set(["inventory_failure", "connection_failure", "deadline_exceeded", "circuit_open", "unsupported", "output_invalid", "lease_lost"]);
  const targetReasons = new Set(["inventory_read_failure", "transient_target_failure", "permanent_target_failure", "required_permission_missing", "deadline_exceeded", "circuit_currently_open", "target_unsupported", "target_version_unsupported", "target_platform_unsupported", "target_edition_unsupported", "capability_missing", "capability_profile_missing", "capability_profile_stale", "output_validation_failed", "lease_ownership_lost"]);
  if (!timestamp(value.snapshotUtc) || typeof value.source !== "string" || !sources.has(value.source) || typeof value.sourceState !== "string" || !states.has(value.sourceState) || !coverage.has(String(value.coverage)) || typeof value.fresh !== "boolean" || typeof value.truncated !== "boolean" || value.contentAvailable !== false || !Array.isArray(raw) || raw.length > 256 || rawCatalog !== undefined && (!Array.isArray(rawCatalog) || rawCatalog.length > 256) || value.reason !== undefined && value.reason !== null && (typeof value.reason !== "string" || value.reason.length > 128) || value.targetStatus !== undefined && value.targetStatus !== null && (typeof value.targetStatus !== "string" || !targetStatuses.has(value.targetStatus)) || value.targetReason !== undefined && value.targetReason !== null && (typeof value.targetReason !== "string" || !targetReasons.has(value.targetReason))) throw new Error("Query performance status response was outside its bounds.");
  const targetFailure = value.targetStatus !== undefined && value.targetStatus !== null;
  const targetReasonByStatus: Record<string, string[]> = { inventory_failure: ["inventory_read_failure"], connection_failure: ["transient_target_failure", "permanent_target_failure", "required_permission_missing"], deadline_exceeded: ["deadline_exceeded"], circuit_open: ["circuit_currently_open"], unsupported: ["target_unsupported", "target_version_unsupported", "target_platform_unsupported", "target_edition_unsupported", "capability_missing", "capability_profile_missing", "capability_profile_stale"], output_invalid: ["output_validation_failed"], lease_lost: ["lease_ownership_lost"] };
  const hasTargetReason = value.targetReason !== undefined && value.targetReason !== null;
  if (targetFailure !== hasTargetReason || targetFailure && (value.source !== "unavailable" || value.sourceState !== "unavailable" || value.coverage !== "unavailable" || value.fresh !== false || typeof value.targetReason !== "string" || !targetReasonByStatus[String(value.targetStatus)]?.includes(value.targetReason))) throw new Error("Target failure evidence was inconsistent.");
  const seen = new Set<number>();
  const parsed = raw.map(x => { if (typeof x !== "object" || x === null) throw new Error("Database status was invalid."); const s = x as Record<string, unknown>; const databaseId = s.databaseId; const status = s.status; const sourceState = s.sourceState; const reason = s.reason; const fallbackAttempted = s.fallbackAttempted; const truncated = s.truncated; const lossKind = s.lossKind; const sourceRowsRead = s.sourceRowsRead; const responseBytes = s.responseBytes; const queryStoreState = typeof sourceState === "string" && states.has(sourceState) && ["read_write", "read_only", "disabled", "unsupported", "permission_denied", "read_failure", "timed_out"].includes(sourceState); const queryStoreStatus = typeof status === "string" && status.startsWith("query_store_"); const planCacheStatus = status === "plan_cache_rows" || status === "plan_cache_empty" || status === "plan_cache_permission_denied" || status === "plan_cache_read_failure" || status === "plan_cache_timed_out"; const compatible = queryStoreStatus ? ((status === "query_store_rows" || status === "query_store_empty") ? (sourceState === "read_write" || sourceState === "read_only") : status.endsWith("disabled") ? sourceState === "disabled" : status.endsWith("unsupported") ? sourceState === "unsupported" : status.endsWith("permission_denied") ? sourceState === "permission_denied" : status.endsWith("read_failure") ? sourceState === "read_failure" : status.endsWith("timed_out") ? sourceState === "timed_out" : false) : planCacheStatus ? fallbackAttempted === true && queryStoreState : status === "output_capped" && truncated === true && queryStoreState;
    const lossConsistent = typeof lossKind === "string" && (lossKind === "none" ? truncated === false : truncated === true);
    const minimumLostItems = s.minimumLostItems; const lossCountIsExact = s.lossCountIsExact; const minimumLostBytes = s.minimumLostBytes;
    if (typeof databaseId !== "number" || !Number.isInteger(databaseId) || databaseId <= 0 || databaseId > 32767 || seen.has(databaseId) || typeof status !== "string" || !databaseStatuses.has(status) || typeof sourceState !== "string" || !states.has(sourceState) || sourceState === "mixed" || sourceState === "unavailable" || typeof reason !== "string" || !statusReasons.has(reason) || !statusReasonCompatible(status, reason) || typeof fallbackAttempted !== "boolean" || typeof truncated !== "boolean" || typeof lossKind !== "string" || !lossKinds.has(lossKind) || !lossConsistent || typeof sourceRowsRead !== "number" || !Number.isInteger(sourceRowsRead) || sourceRowsRead < 0 || sourceRowsRead > 2001 || typeof responseBytes !== "number" || !Number.isInteger(responseBytes) || responseBytes < 0 || responseBytes > maximumResponseBytes || typeof minimumLostItems !== "number" || !Number.isInteger(minimumLostItems) || minimumLostItems < 0 || minimumLostItems > 20000 || typeof lossCountIsExact !== "boolean" || typeof minimumLostBytes !== "number" || !Number.isInteger(minimumLostBytes) || minimumLostBytes < 0 || minimumLostBytes > maximumResponseBytes || lossKind === "none" && (minimumLostItems !== 0 || minimumLostBytes !== 0 || !lossCountIsExact) || !compatible) throw new Error("Database status was outside its bounds."); seen.add(databaseId); return { databaseId, status, sourceState, reason, fallbackAttempted, truncated, lossKind, sourceRowsRead, responseBytes, minimumLostItems, lossCountIsExact, minimumLostBytes } satisfies QueryPerformanceDatabaseStatus; });
  const catalogSeen = new Set<number>();
  const catalogInput = rawCatalog === undefined ? [] : rawCatalog as unknown[];
  const catalog: QueryPerformanceDatabaseCatalog[] = catalogInput.map(x => { if (typeof x !== "object" || x === null) throw new Error("Database catalog entry was invalid."); const entry = x as Record<string, unknown>; const databaseId = entry.databaseId; const databaseName = entry.databaseName; if (typeof databaseId !== "number" || !Number.isInteger(databaseId) || databaseId <= 0 || databaseId > 32767 || catalogSeen.has(databaseId) || typeof databaseName !== "string" || databaseName.length === 0 || databaseName.length > 1024) throw new Error("Database catalog entry was outside its bounds."); catalogSeen.add(databaseId); return { databaseId, databaseName } satisfies QueryPerformanceDatabaseCatalog; });
  return { targetId: instanceId, snapshotUtc: value.snapshotUtc as string, source: value.source as QueryPerformanceStatus["source"], sourceState: value.sourceState, coverage: String(value.coverage), fresh: value.fresh, truncated: value.truncated, reason: typeof value.reason === "string" ? value.reason : undefined, targetStatus: typeof value.targetStatus === "string" ? value.targetStatus : undefined, targetReason: typeof value.targetReason === "string" ? value.targetReason : undefined, databaseStatuses: parsed, databaseCatalog: catalog };
}
export async function getQueryPerformanceHistory(instanceId: string, databaseId: number, queryFingerprint: string, fromUtc: string, toUtc: string, signal?: AbortSignal, cursor?: string): Promise<QueryPerformanceHistoryPage> {
  if (!Number.isInteger(databaseId) || databaseId <= 0 || databaseId > 32767 || !digest(queryFingerprint)) throw new Error("Query identity was invalid.");
  if (!timestamp(fromUtc) || !timestamp(toUtc) || Date.parse(toUtc) <= Date.parse(fromUtc) || Date.parse(toUtc) - Date.parse(fromUtc) > 7 * 24 * 60 * 60 * 1000) throw new Error("Query performance history window was invalid.");
  if (cursor !== undefined && (cursor.length === 0 || cursor.length > 1024)) throw new Error("Query performance history cursor was invalid.");
  const cursorQuery = cursor === undefined ? "" : `&cursor=${encodeURIComponent(cursor)}`;
  const value = await readJson(`/api/v1/observation-targets/${encodeURIComponent(instanceId)}/query-performance/databases/${databaseId}/history/${queryFingerprint}?fromUtc=${encodeURIComponent(fromUtc)}&toUtc=${encodeURIComponent(toUtc)}&limit=200${cursorQuery}`, instanceId, signal) as { databaseId?: unknown; queryFingerprint?: unknown; items?: unknown; snapshotUtc?: unknown; fromUtc?: unknown; toUtc?: unknown; nextCursor?: unknown };
  if (value.databaseId !== databaseId || value.queryFingerprint !== queryFingerprint || !timestamp(value.snapshotUtc) || typeof value.fromUtc !== "string" || typeof value.toUtc !== "string" || canonicalInstant(value.fromUtc) !== canonicalInstant(fromUtc) || canonicalInstant(value.toUtc) !== canonicalInstant(toUtc) || !timestamp(value.fromUtc) || !timestamp(value.toUtc) || !Array.isArray(value.items) || value.items.length > 200 || value.nextCursor !== undefined && value.nextCursor !== null && (typeof value.nextCursor !== "string" || value.nextCursor.length === 0 || value.nextCursor.length > 1024)) throw new Error("Query performance history response was outside its bounds.");
  const items = value.items.map(raw => { const x = raw as Record<string, unknown>; if (x.databaseId !== databaseId || x.queryFingerprint !== queryFingerprint || !metric(x.cpuMilliseconds) || !metric(x.durationMilliseconds) || !metric(x.executions) || !metric(x.logicalReads) || !metric(x.writes) || !metric(x.rows)) throw new Error("Query performance history metrics were invalid."); const base = item({ ...x, metric: "cpu", value: x.cpuMilliseconds ?? null }, "cpu"); if (Date.parse(base.intervalStartUtc) < Date.parse(fromUtc) || Date.parse(base.intervalEndUtc) > Date.parse(toUtc)) throw new Error("Query performance history item was outside its bound window."); return { ...base, metrics: { cpuMilliseconds: x.cpuMilliseconds ?? null, durationMilliseconds: x.durationMilliseconds ?? null, executions: x.executions ?? null, logicalReads: x.logicalReads ?? null, writes: x.writes ?? null, rows: x.rows ?? null } }; });
  return { repositoryTimeUtc: value.snapshotUtc, items, nextCursor: typeof value.nextCursor === "string" ? value.nextCursor : undefined };
}
export async function getQueryPerformancePlan(instanceId: string, databaseId: number, queryFingerprint: string, planFingerprint: string, signal?: AbortSignal): Promise<QueryPerformancePlan> {
  if (!Number.isInteger(databaseId) || databaseId <= 0 || databaseId > 32767 || !digest(queryFingerprint) || !digest(planFingerprint)) throw new Error("Plan identity was invalid.");
  const value = await readJson(`/api/v1/observation-targets/${encodeURIComponent(instanceId)}/query-performance/databases/${databaseId}/plans/${planFingerprint}?queryFingerprint=${queryFingerprint}`, instanceId, signal) as Record<string, unknown>;
  if (value.databaseId !== databaseId || value.queryFingerprint !== queryFingerprint || value.planFingerprint !== planFingerprint || !sources.has(String(value.source)) || value.source === "mixed" || value.source === "unavailable" || !timestamp(value.observedAtUtc) || !coverage.has(String(value.coverage)) || value.contentAvailable !== false) throw new Error("Query performance plan response was outside its bounds.");
  return { targetId: instanceId, databaseId, queryFingerprint, planFingerprint, source: value.source as QueryPerformancePlan["source"], observedAtUtc: value.observedAtUtc, coverage: String(value.coverage), contentAvailable: false };
}
