import { parseAnalyticsSurfacePage, parseBaselines, parseComparison, parseForecasts, parseIncidentsSurfacePage, parseMetricSeries, parseMutationReceipt, parseRetentionExecution, parseRetentionPolicy, parseRetentionPreview, parseRollupPage } from "./analyticsParser.ts";
import type { AnalyticsComparison, AnalyticsMutationReceipt, AnalyticsSurface, AnalyticsSurfacePage, MetricSeries, RetentionExecutionResult, RetentionPolicyResult, RetentionPreview, RollupPage } from "./analyticsTypes";

export class AnalyticsRequestError extends Error { public readonly status: number; public constructor(status: number, message: string) { super(message); this.name = "AnalyticsRequestError"; this.status = status; } }
const safeStatus = (status: number) => status === 400 || status === 422 ? "The analytics request or cursor is invalid." : status === 403 ? "You are not authorized to view this analytics surface." : status === 404 ? "No analytics data is available." : status === 409 ? "The analytics generation changed; refresh and try again." : status === 410 ? "This data is blocked by the retention policy." : status === 202 ? "Analytics backfill is still running." : status === 504 ? "The analytics request exceeded its execution limit." : "The analytics service is temporarily unavailable.";
export const analyticsSurfaceLimits: Readonly<Record<AnalyticsSurface, number>> = { jobs: 100, backfill: 100, "host/status": 200, "host/metrics": 200, "replication/status": 200, "replication/evidence": 200, "diagnostics/search": 100, incidents: 100, "evidence-packets": 200 };
function targetPath(targetId: string): string { if (!/^[0-9a-fA-F-]{1,64}$/.test(targetId)) throw new Error("Invalid target id."); return encodeURIComponent(targetId); }
async function readJson(path: string, signal: AbortSignal, init?: RequestInit): Promise<unknown> { const response = await fetch(path, { credentials: "same-origin", headers: { Accept: "application/json", ...(init?.body ? { "Content-Type": "application/json" } : {}) }, signal, ...init }); if (!response.ok) throw new AnalyticsRequestError(response.status, safeStatus(response.status)); const length = Number(response.headers.get("content-length") ?? 0); if (Number.isFinite(length) && length > 1_048_576) throw new AnalyticsRequestError(413, "The analytics response is too large."); if (!response.body) return response.json(); const reader = response.body.getReader(); const chunks: Uint8Array[] = []; let total = 0; try { while (true) { const part = await reader.read(); if (part.done) break; total += part.value.byteLength; if (total > 1_048_576) { await reader.cancel(); throw new AnalyticsRequestError(413, "The analytics response is too large."); } chunks.push(part.value); } } finally { reader.releaseLock(); } const bytes = new Uint8Array(total); let offset = 0; for (const chunk of chunks) { bytes.set(chunk, offset); offset += chunk.byteLength; } return JSON.parse(new TextDecoder().decode(bytes)); }
function query(params: Record<string, string | number | undefined>): string { const result = new URLSearchParams(); for (const [key, value] of Object.entries(params)) if (value !== undefined) result.set(key, String(value)); return result.toString(); }
export async function getMetricSeries(targetId: string, metric: string, signal: AbortSignal): Promise<MetricSeries> { const result = await readJson(`/api/v1/observation-targets/${targetPath(targetId)}/analytics/series?${query({ metricKey: metric, limit: 1000 })}`, signal); return parseMetricSeries(result, targetId); }
export async function getRollups(targetId: string, metric: string, signal: AbortSignal, cursor?: string): Promise<RollupPage> { const result = await readJson(`/api/v1/observation-targets/${targetPath(targetId)}/analytics/rollups?${query({ metricKey: metric, interval: "hour", limit: 200, cursor })}`, signal); return parseRollupPage(result, targetId); }
export async function getAnalyticsSurface<T = Record<string, unknown>>(targetId: string, surface: AnalyticsSurface, signal: AbortSignal, options: { fromUtc?: string; toUtc?: string; limit?: number; cursor?: string; expectedTargetRevision?: number } = {}): Promise<AnalyticsSurfacePage<T>> { const pathSurface = surface === "backfill" ? "backfill" : surface; const limit = options.limit ?? analyticsSurfaceLimits[surface]; const result = await readJson(`/api/v1/observation-targets/${targetPath(targetId)}/analytics/${pathSurface}?${query({ fromUtc: options.fromUtc, toUtc: options.toUtc, limit, cursor: options.cursor })}`, signal); return surface === "incidents" ? parseIncidentsSurfacePage<T>(result, targetId, options.expectedTargetRevision) : parseAnalyticsSurfacePage<T>(result, surface, targetId, options.expectedTargetRevision); }
export const getAnalyticsPage = getAnalyticsSurface;
export const getJobs = <T = Record<string, unknown>>(targetId: string, signal: AbortSignal, options?: Parameters<typeof getAnalyticsSurface>[3]) => getAnalyticsSurface<T>(targetId, "jobs", signal, options);
export const getBackfill = <T = Record<string, unknown>>(targetId: string, signal: AbortSignal, options?: Parameters<typeof getAnalyticsSurface>[3]) => getAnalyticsSurface<T>(targetId, "backfill", signal, options);
export const getHostStatus = <T = Record<string, unknown>>(targetId: string, signal: AbortSignal, options?: Parameters<typeof getAnalyticsSurface>[3]) => getAnalyticsSurface<T>(targetId, "host/status", signal, options);
export const getHostMetrics = <T = Record<string, unknown>>(targetId: string, signal: AbortSignal, options?: Parameters<typeof getAnalyticsSurface>[3]) => getAnalyticsSurface<T>(targetId, "host/metrics", signal, options);
export const getReplicationStatus = <T = Record<string, unknown>>(targetId: string, signal: AbortSignal, options?: Parameters<typeof getAnalyticsSurface>[3]) => getAnalyticsSurface<T>(targetId, "replication/status", signal, options);
export const getReplicationEvidence = <T = Record<string, unknown>>(targetId: string, signal: AbortSignal, options?: Parameters<typeof getAnalyticsSurface>[3]) => getAnalyticsSurface<T>(targetId, "replication/evidence", signal, options);
export const searchDiagnostics = <T = Record<string, unknown>>(targetId: string, signal: AbortSignal, options?: Parameters<typeof getAnalyticsSurface>[3]) => getAnalyticsSurface<T>(targetId, "diagnostics/search", signal, options);
export const getIncidents = <T = Record<string, unknown>>(targetId: string, signal: AbortSignal, options?: Parameters<typeof getAnalyticsSurface>[3]) => getAnalyticsSurface<T>(targetId, "incidents", signal, options);
export const getEvidencePackets = <T = Record<string, unknown>>(targetId: string, signal: AbortSignal, options?: Parameters<typeof getAnalyticsSurface>[3]) => getAnalyticsSurface<T>(targetId, "evidence-packets", signal, options);
export async function compareAnalytics(targetId: string, metricKey: string, windows: { leftFromUtc: string; leftToUtc: string; rightFromUtc: string; rightToUtc: string }, signal: AbortSignal): Promise<AnalyticsComparison> { const result = await readJson(`/api/v1/observation-targets/${targetPath(targetId)}/analytics/compare?${query({ metricKey, ...windows })}`, signal); return parseComparison(result, targetId); }
export async function getBaselines(targetId: string, metricKey: string, signal: AbortSignal): Promise<readonly import("./analyticsTypes").Baseline[]> { const result = await readJson(`/api/v1/observation-targets/${targetPath(targetId)}/analytics/baselines?${query({ metricKey, limit: 200 })}`, signal); return parseBaselines(result, targetId); }
export async function getForecasts(targetId: string, metricKey: string, signal: AbortSignal, horizonDays = 30): Promise<readonly import("./analyticsTypes").Forecast[]> { const result = await readJson(`/api/v1/observation-targets/${targetPath(targetId)}/analytics/forecasts?${query({ metricKey, horizonDays })}`, signal); return parseForecasts(result, targetId); }
export async function getRetentionPolicy(dataClass: string, signal: AbortSignal): Promise<RetentionPolicyResult> { const result = await readJson(`/api/v1/retention/policies/${encodeURIComponent(dataClass)}`, signal); return parseRetentionPolicy(result); }
export async function getRetentionPreview(signal: AbortSignal, limit = 100, cursor?: string): Promise<RetentionPreview> { if (!Number.isSafeInteger(limit) || limit < 1 || limit > 1024) throw new Error("Invalid retention preview limit."); if (cursor !== undefined && (!/^[A-Za-z0-9_-]{1,1024}$/.test(cursor))) throw new Error("Invalid retention preview cursor."); const result = await readJson(`/api/v1/retention/preview?${query({ limit, cursor })}`, signal); return parseRetentionPreview(result); }
function jsonBody(body: unknown): string { let value: string; try { value = JSON.stringify(body); } catch { throw new Error("Mutation body is not JSON serializable."); } const bytes = new TextEncoder().encode(value); if (bytes.byteLength > 16 * 1024) throw new Error("Mutation body exceeds 16 KiB."); return value; }
function objectBody(body: unknown, fields: readonly string[]): Record<string, unknown> { if (!body || typeof body !== "object" || Array.isArray(body)) throw new Error("Mutation body must be an object."); const value = body as Record<string, unknown>; if (Object.keys(value).some(key => !fields.includes(key))) throw new Error("Mutation body contains an unknown field."); return value; }
function guidBody(value: unknown, name: string): string { if (typeof value !== "string" || !/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)) throw new Error(`Invalid ${name}.`); return value; }
function utcBody(value: unknown, name: string): string { if (typeof value !== "string" || !/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,7})?Z$/.test(value) || !Number.isFinite(Date.parse(value))) throw new Error(`Invalid ${name}.`); return value; }
function retentionBody(body: unknown, operation: "detach" | "drop"): Record<string, unknown> { const value = objectBody(body, ["operation", "operationId", "executionId", "dataClass", "parentSchema", "parentTable", "partitionName", "expectedPolicyRevision", "changeReason", "correlationId", "requestDigest"]); if (value.operation !== undefined && value.operation !== operation) throw new Error("Mismatched retention operation."); guidBody(value.operationId, "operationId"); guidBody(value.executionId, "executionId"); if (typeof value.dataClass !== "string" || !/^m10_(host_metrics|replication|rollups|evidence)$/.test(value.dataClass)) throw new Error("Invalid dataClass."); for (const [name, max] of [["parentSchema", 128], ["parentTable", 128], ["partitionName", 128]] as const) if (typeof value[name] !== "string" || !/^[A-Za-z0-9_.-]{1,128}$/.test(value[name] as string) || (value[name] as string).length > max) throw new Error(`Invalid ${name}.`); if (!Number.isSafeInteger(value.expectedPolicyRevision) || Number(value.expectedPolicyRevision) < 1) throw new Error("Invalid expectedPolicyRevision."); if (typeof value.changeReason !== "string" || value.changeReason.length < 1 || value.changeReason.length > 512) throw new Error("Invalid changeReason."); guidBody(value.correlationId, "correlationId"); if (typeof value.requestDigest !== "string" || !/^[0-9a-f]{64}$/i.test(value.requestDigest)) throw new Error("Invalid requestDigest."); return value; }
function attestationBody(body: unknown): Record<string, unknown> { const value = objectBody(body, ["attestationId", "attestedBy", "backupSetReference", "expiresAtUtc", "digest", "correlationId", "changeReason", "requestDigest"]); guidBody(value.attestationId, "attestationId"); if (typeof value.attestedBy !== "string" || value.attestedBy.length < 1 || value.attestedBy.length > 256 || typeof value.backupSetReference !== "string" || value.backupSetReference.length < 1 || value.backupSetReference.length > 512) throw new Error("Invalid attestation text."); if (Date.parse(utcBody(value.expiresAtUtc, "expiresAtUtc")) <= Date.now()) throw new Error("Attestation expiry must be future."); if (typeof value.digest !== "string" || !/^[0-9a-f]{64}$/i.test(value.digest)) throw new Error("Invalid digest."); if (value.requestDigest !== undefined && (typeof value.requestDigest !== "string" || !/^[0-9a-f]{64}$/i.test(value.requestDigest))) throw new Error("Invalid requestDigest."); guidBody(value.correlationId, "correlationId"); if (typeof value.changeReason !== "string" || value.changeReason.length < 1 || value.changeReason.length > 512) throw new Error("Invalid changeReason."); return value; }
async function mutation(path: string, body: unknown, signal: AbortSignal): Promise<AnalyticsMutationReceipt> { const encoded = jsonBody(body); const result = await readJson(path, signal, { method: "POST", body: encoded }); return parseMutationReceipt(result); }
async function retentionMutation(path: string, body: unknown, signal: AbortSignal): Promise<RetentionExecutionResult> { const encoded = jsonBody(body); return parseRetentionExecution(await readJson(path, signal, { method: "POST", body: encoded })); }
export function bindHost(targetId: string, body: unknown, signal: AbortSignal, expectedRevision: number): Promise<AnalyticsMutationReceipt> { const value = objectBody(body, ["targetId", "hostId", "hostName", "identityFingerprint", "bindingRevision", "profileRevision", "expectedRevision", "operationId", "requestDigest", "correlationId", "changeReason", "profile"]); if (String(value.targetId).toLowerCase() !== targetId.toLowerCase()) throw new Error("Mismatched targetId."); guidBody(value.targetId, "targetId"); guidBody(value.hostId, "hostId"); if (typeof value.hostName !== "string" || value.hostName.length < 1 || value.hostName.length > 512) throw new Error("Invalid hostName."); if (typeof value.identityFingerprint !== "string" || !/^[0-9a-f]{64}$/i.test(value.identityFingerprint)) throw new Error("Invalid identityFingerprint."); if (typeof value.requestDigest !== "string" || !/^[0-9a-f]{64}$/i.test(value.requestDigest)) throw new Error("Invalid requestDigest."); if (!value.profile || typeof value.profile !== "object" || Array.isArray(value.profile)) throw new Error("Invalid profile."); const profile = value.profile as Record<string, unknown>; if (Object.keys(profile).some(k => !["osFamily", "osVersion", "cpuCount", "memoryBytes", "capabilityState"].includes(k)) || typeof profile.osFamily !== "string" || profile.osFamily.length < 1 || profile.osFamily.length > 128 || typeof profile.osVersion !== "string" || profile.osVersion.length < 1 || profile.osVersion.length > 128 || !Number.isSafeInteger(profile.cpuCount) || Number(profile.cpuCount) < 1 || Number(profile.cpuCount) > 65536 || !Number.isSafeInteger(profile.memoryBytes) || Number(profile.memoryBytes) < 0 || Number(profile.memoryBytes) > 2 ** 60 || !["available", "partial", "unsupported", "permission_denied"].includes(String(profile.capabilityState))) throw new Error("Invalid profile."); if (!Number.isSafeInteger(value.bindingRevision) || Number(value.bindingRevision) < 0 || !Number.isSafeInteger(value.profileRevision) || Number(value.profileRevision) < 1) throw new Error("Invalid binding/profile revision."); if (!Number.isSafeInteger(expectedRevision) || expectedRevision < 1) throw new Error("Invalid expectedRevision."); if (value.expectedRevision !== expectedRevision) throw new Error("Mismatched expectedRevision."); guidBody(value.operationId, "operationId"); guidBody(value.correlationId, "correlationId"); if (typeof value.changeReason !== "string" || value.changeReason.length < 1 || value.changeReason.length > 512) throw new Error("Invalid changeReason."); return mutation(`/api/v1/observation-targets/${targetPath(targetId)}/analytics/host-binding?expectedRevision=${expectedRevision}&operationId=${encodeURIComponent(String(value.operationId))}`, body, signal); }
export function startBackfill(targetId: string, body: unknown, signal: AbortSignal): Promise<AnalyticsMutationReceipt> { const value = objectBody(body, ["targetId", "fromUtc", "toUtc", "metricKey", "expectedRevision", "operationId", "requestDigest", "correlationId", "changeReason"]); if (String(value.targetId).toLowerCase() !== targetId.toLowerCase()) throw new Error("Mismatched targetId."); guidBody(value.targetId, "targetId"); const fromUtc = utcBody(value.fromUtc, "fromUtc"), toUtc = utcBody(value.toUtc, "toUtc"); if (Date.parse(toUtc) <= Date.parse(fromUtc) || Date.parse(toUtc) - Date.parse(fromUtc) > 90 * 86400000) throw new Error("Invalid backfill window."); const metricKey = value.metricKey === null ? undefined : value.metricKey; if (metricKey !== undefined && (typeof metricKey !== "string" || !/^[a-z][a-z0-9._-]{0,127}$/.test(metricKey))) throw new Error("Invalid metricKey."); if (!Number.isSafeInteger(value.expectedRevision) || Number(value.expectedRevision) < 1) throw new Error("Invalid expectedRevision."); const expectedRevision = Number(value.expectedRevision); guidBody(value.operationId, "operationId"); if (typeof value.requestDigest !== "string" || !/^[0-9a-f]{64}$/i.test(value.requestDigest)) throw new Error("Invalid requestDigest."); guidBody(value.correlationId, "correlationId"); if (typeof value.changeReason !== "string" || value.changeReason.length < 1 || value.changeReason.length > 512) throw new Error("Invalid changeReason."); return mutation(`/api/v1/observation-targets/${targetPath(targetId)}/analytics/backfill?${query({ fromUtc, toUtc, metricKey, expectedRevision })}`, body, signal); }
export async function updateRetentionPolicy(dataClass: string, body: unknown, signal: AbortSignal): Promise<RetentionPolicyResult> { if (!["m10_host_metrics", "m10_replication", "m10_rollups", "m10_evidence"].includes(dataClass)) throw new Error("Invalid retention data class."); const value = objectBody(body, ["dataClass", "enabled", "retainFor", "minimumPartitionsToKeep", "expectedRevision", "changeReason"]); if (value.dataClass !== dataClass || typeof value.enabled !== "boolean" || value.retainFor !== null && typeof value.retainFor !== "string" || !Number.isSafeInteger(value.minimumPartitionsToKeep) || Number(value.minimumPartitionsToKeep) < 1 || Number(value.minimumPartitionsToKeep) > 10000 || !Number.isSafeInteger(value.expectedRevision) || Number(value.expectedRevision) < 1 || typeof value.changeReason !== "string" || value.changeReason.length < 1 || value.changeReason.length > 512) throw new Error("Invalid retention policy body."); const encoded = jsonBody(body); return parseRetentionPolicy(await readJson(`/api/v1/retention/policies/${encodeURIComponent(dataClass)}`, signal, { method: "PUT", body: encoded })); }
export function detachRetention(body: unknown, signal: AbortSignal): Promise<RetentionExecutionResult> { retentionBody(body, "detach"); return retentionMutation("/api/v1/retention/detach", body, signal); }
export function dropRetention(body: unknown, signal: AbortSignal): Promise<RetentionExecutionResult> { retentionBody(body, "drop"); return retentionMutation("/api/v1/retention/drop", body, signal); }
export function recordAttestation(body: unknown, signal: AbortSignal): Promise<AnalyticsMutationReceipt> { attestationBody(body); return mutation("/api/v1/retention/attestations", body, signal); }
