export type AnalyticsVisibility = "complete" | "partial" | "unavailable" | "unsupported";
export type AnalyticsSurfaceState = "complete" | "partial" | "visibility_gap" | "no_data" | "stale" | "backfilling" | "unavailable" | "unsupported" | "permission_denied" | "retention_blocked";
export type AnalyticsPanelState = "loading" | "ready" | "no-data" | "degraded" | "permission-denied" | "unsupported" | "stale" | "partial" | "low-confidence" | "backfilling" | "cursor-invalid" | "retention-blocked";
export type AnalyticsSurface = "jobs" | "backfill" | "host/status" | "host/metrics" | "replication/status" | "replication/evidence" | "diagnostics/search" | "incidents" | "evidence-packets";
export interface MetricSeriesItem { readonly observedAtUtc: string; readonly value: number; readonly dimensions: Readonly<Record<string, string>>; }
export interface MetricSeries { readonly targetId: string; readonly metricKey: string; readonly items: readonly MetricSeriesItem[]; readonly state: AnalyticsSurfaceState; readonly fromUtc: string; readonly toUtc: string; }
export interface Rollup { readonly bucketStartUtc: string; readonly bucketEndUtc: string; readonly metricKey: string; readonly count: number; readonly mean: number | null; readonly expected: number; readonly coverage: number; readonly truncated: boolean; readonly sourceCutoffUtc: string | null; readonly visibilityState?: AnalyticsVisibility; readonly sum?: number | null; readonly min?: number | null; readonly max?: number | null; readonly last?: number | null; }
export interface RollupPage { readonly targetId: string; readonly metricKey: string; readonly items: readonly Rollup[]; readonly hasMore: boolean; readonly nextCursor?: string | null; readonly state?: AnalyticsSurfaceState; readonly snapshotUtc?: string; readonly sourceCutoffUtc?: string; readonly targetRevision?: number; readonly generation?: number; }
export interface AnalyticsSurfacePage<T = Record<string, unknown>> { readonly targetId: string; readonly surface: AnalyticsSurface; readonly items: readonly T[]; readonly state: AnalyticsSurfaceState; readonly nextCursor: string | null; readonly cutoffUtc: string; readonly snapshotUtc: string; readonly targetRevision: number; readonly generation: number; readonly fromUtc: string; readonly toUtc: string; }
export interface AnalyticsComparison { readonly leftValue: number | null; readonly rightValue: number | null; readonly delta: number | null; readonly percent: number | null; readonly leftSamples: number; readonly rightSamples: number; readonly complete: boolean; }
export interface Baseline { readonly metricKey: string; readonly hourOfWeek: number; readonly completeDays: number; readonly sampleCount: number; readonly median: number | null; readonly mad: number | null; readonly p10: number | null; readonly p90: number | null; readonly coverage: number; readonly confidence: number; readonly windowStartUtc?: string | null; readonly windowEndUtc?: string | null; readonly generation?: number; readonly visibilityState?: AnalyticsVisibility; }
export interface Forecast { readonly metricKey: string; readonly horizonStartUtc: string; readonly horizonEndUtc: string; readonly estimate: number | null; readonly lowerBound: number | null; readonly upperBound: number | null; readonly slopePerDay: number | null; readonly confidence: number; readonly residual: number; readonly forecastId?: string | null; readonly model?: string; readonly sourceGeneration?: number; readonly visibilityState?: AnalyticsVisibility; }
export interface RetentionPolicy { readonly dataClass: string; readonly enabled: boolean; readonly retainFor: string | null; readonly minimumPartitionsToKeep: number; }
export interface RetentionPolicyResult { readonly policy: RetentionPolicy; readonly revision: number; readonly readAtUtc: string; }
export interface RetentionPreviewEntry { readonly dataClass: string; readonly parentSchema: string; readonly parentTable: string; readonly partitionName: string; readonly rangeStartUtc: string; readonly rangeEndUtc: string; readonly eligible: boolean; readonly reason: string; }
export interface RetentionPreview { readonly entries: readonly RetentionPreviewEntry[]; readonly truncated: boolean; readonly nextCursor: string | null; readonly evaluatedAtUtc: string; }
export interface AnalyticsMutationReceipt { readonly operationId: string; readonly state: string; readonly revision: number | null; readonly acceptedAtUtc: string; }
export interface RetentionExecutionResult { readonly executionId: string; readonly state: number; readonly blockReason: number | null; readonly dropAfterUtc: string | null; readonly failureCode: string | null; }
