import type { AnalyticsComparison, AnalyticsSurface, AnalyticsSurfacePage, Baseline, Forecast, MetricSeries, Rollup, RollupPage, RetentionPolicyResult, RetentionPreview } from "./analyticsTypes";

const metricKey = /^[a-z][a-z0-9._-]{0,127}$/;
const catalogMetrics = new Set(["host.cpu.percent", "host.memory.available_bytes", "host.memory.committed_bytes", "host.volume.free_bytes", "host.volume.total_bytes", "host.volume.queue_length", "host.volume.read_latency_ms", "host.volume.write_latency_ms", "replication.pending_commands", "replication.latency_seconds"]);
const states = new Set(["complete", "partial", "visibility_gap", "no_data", "stale", "backfilling", "unavailable", "unsupported", "permission_denied", "retention_blocked"]);
const visibility = new Set(["complete", "partial", "unavailable", "unsupported"]);
const surfaces = new Set<AnalyticsSurface>(["jobs", "backfill", "host/status", "host/metrics", "replication/status", "replication/evidence", "diagnostics/search", "incidents", "evidence-packets"]);
const surfaceKeys: Record<AnalyticsSurface, readonly string[]> = {
  "host/status": ["hostId", "targetRevision", "bindingRevision", "hostName", "bindingState", "capabilityState", "observedAtUtc"],
  "host/metrics": ["observedAtUtc", "runId", "metricKey", "value", "dimensions", "targetRevision"],
  "replication/status": ["observedAtUtc", "runId", "role", "synchronizationState", "sendQueueBytes", "redoQueueBytes", "visibilityScope", "coverage", "visibilityGap", "stateAvailable", "targetRevision"],
  "replication/evidence": ["observedAtUtc", "runId", "role", "synchronizationState", "sendQueueBytes", "redoQueueBytes", "visibilityScope", "coverage", "visibilityGap", "stateAvailable", "targetRevision"],
  "diagnostics/search": ["occurredAtUtc", "eventId", "eventKind", "severity", "safeMetadata", "collectedAtUtc", "targetRevision"],
  jobs: ["jobId", "jobKind", "status", "requestedAtUtc", "startedAtUtc", "completedAtUtc", "attempt", "targetRevision"], backfill: ["jobId", "jobKind", "status", "requestedAtUtc", "startedAtUtc", "completedAtUtc", "attempt", "targetRevision"],
  incidents: ["threadId", "openedAtUtc", "closedAtUtc", "currentGeneration", "targetRevision"],
  "evidence-packets": ["occurredAtUtc", "packetId", "evidenceKind", "sourceRunId", "sourceDigest", "confidence", "visibilityState", "targetRevision"]
};
function object(value: unknown): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("Invalid analytics response"); return value as Record<string, unknown>; }
function keys(value: Record<string, unknown>, allowed: readonly string[], label: string): void { if (Object.keys(value).some(key => !allowed.includes(key))) throw new Error(`Unexpected ${label} field`); }
function required(value: Record<string, unknown>, names: readonly string[], label: string): void { if (names.some(name => !Object.prototype.hasOwnProperty.call(value, name))) throw new Error(`Missing ${label} field`); }
function text(value: unknown, label: string, max = 1024): string { if (typeof value !== "string" || value.length === 0 || value.length > max || /[\u0000-\u001f\u007f]/.test(value)) throw new Error(`Invalid ${label}`); return value; }
function number(value: unknown, label: string): number { if (typeof value !== "number" || !Number.isFinite(value)) throw new Error(`Invalid ${label}`); return value; }
function integer(value: unknown, label: string): number { const n = number(value, label); if (!Number.isSafeInteger(n) || n < 0) throw new Error(`Invalid ${label}`); return n; }
function guid(value: unknown, label: string, nullable = false): string | null { if (value == null && nullable) return null; if (typeof value !== "string" || !/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)) throw new Error(`Invalid ${label}`); return value; }
export function utc(value: unknown, label: string, nullable = false): string | null { if (value == null && nullable) return null; if (typeof value !== "string" || !/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,7})?Z$/.test(value) || !Number.isFinite(Date.parse(value))) throw new Error(`Invalid ${label}`); return value; }
function window(from: unknown, to: unknown, label: string): [string, string] | undefined { if (from === undefined && to === undefined) return undefined; const start = utc(from, `${label} start`)!; const end = utc(to, `${label} end`)!; if (Date.parse(end) <= Date.parse(start) || Date.parse(end) - Date.parse(start) > 1000 * 60 * 60 * 24 * 366) throw new Error(`Invalid ${label} window`); return [start, end]; }
function cursor(value: unknown): string | null { if (value == null) return null; const result = text(value, "cursor", 1024); if (!/^[-A-Za-z0-9_.:|/+=]+$/.test(result)) throw new Error("Invalid cursor"); return result; }
function boundedState(value: unknown): string { const state = value === undefined ? "complete" : text(value, "state", 32); if (!states.has(state)) throw new Error("Invalid analytics state"); return state; }
function dimensions(value: unknown): Record<string, string> { const row = object(value); if (Object.keys(row).length > 32) throw new Error("Too many dimensions"); const result: Record<string, string> = {}; for (const [key, item] of Object.entries(row)) { if (!/^[A-Za-z0-9_-]{1,64}$/.test(key) || typeof item !== "string" || item.length > 256 || /[\u0000-\u001f\u007f]/.test(item)) throw new Error("Invalid metric dimension"); result[key] = item; } return result; }
function bindTarget(row: Record<string, unknown>, expectedTargetId?: string, expectedRevision?: number): string { const targetId = text(row.targetId, "targetId", 64); if (expectedTargetId !== undefined && targetId.toLowerCase() !== expectedTargetId.toLowerCase()) throw new Error("Analytics target binding mismatch"); if (expectedRevision !== undefined && (!Number.isSafeInteger(expectedRevision) || expectedRevision < 1)) throw new Error("Invalid expected target revision"); return targetId; }
function bindRevision(value: unknown, expectedRevision?: number): number { const revision = integer(value, "targetRevision"); if (revision < 1 || expectedRevision !== undefined && revision !== expectedRevision) throw new Error("Analytics target revision mismatch"); return revision; }
function catalogMetric(value: unknown, label: string): string { if (typeof value !== "string" || !metricKey.test(value) || !catalogMetrics.has(value)) throw new Error(`Invalid ${label}`); return value; }

export function parseMetricSeries(value: unknown, expectedTargetId?: string, expectedRevision?: number): MetricSeries {
  const row = object(value); keys(row, ["targetId", "metricKey", "state", "items", "fromUtc", "toUtc", "targetRevision"], "series"); required(row, ["targetId", "metricKey", "items"], "series");
  const targetId = bindTarget(row, expectedTargetId, expectedRevision); const metric = catalogMetric(row.metricKey, "metric series metric"); if (!Array.isArray(row.items) || row.items.length > 1000) throw new Error("Invalid metric series response");
  const state = boundedState(row.state); const bounds = window(row.fromUtc, row.toUtc, "series"); if (row.targetRevision !== undefined) bindRevision(row.targetRevision, expectedRevision);
  const items = row.items.map(item => { const x = object(item); keys(x, ["observedAtUtc", "value", "dimensions"], "series item"); required(x, ["observedAtUtc", "value", "dimensions"], "series item"); const observedAtUtc = utc(x.observedAtUtc, "observedAtUtc")!; if (bounds && (Date.parse(observedAtUtc) < Date.parse(bounds[0]) || Date.parse(observedAtUtc) >= Date.parse(bounds[1]))) throw new Error("Series item is outside its window"); return { observedAtUtc, value: number(x.value, "value"), dimensions: dimensions(x.dimensions) }; });
  for (let i = 1; i < items.length; i++) if (Date.parse(items[i - 1]!.observedAtUtc) > Date.parse(items[i]!.observedAtUtc)) throw new Error("Metric series is out of order");
  return { targetId, metricKey: metric, items, state: state as MetricSeries["state"], fromUtc: bounds?.[0] ?? "", toUtc: bounds?.[1] ?? "" };
}
export function parseRollupPage(value: unknown, expectedTargetId?: string, expectedRevision?: number): RollupPage {
  const row = object(value); keys(row, ["targetId", "metricKey", "interval", "items", "hasMore", "nextCursor", "state", "fromUtc", "toUtc", "sourceCutoffUtc", "snapshotUtc", "generation", "targetRevision"], "rollup"); required(row, ["targetId", "metricKey", "items", "hasMore"], "rollup");
  const targetId = bindTarget(row, expectedTargetId, expectedRevision); const metric = catalogMetric(row.metricKey, "rollup metric"); if (!Array.isArray(row.items) || row.items.length > 200 || typeof row.hasMore !== "boolean") throw new Error("Invalid rollup response");
  if (row.interval !== undefined && !["5m", "five_minutes", "hour", "day"].includes(String(row.interval))) throw new Error("Invalid rollup interval");
  const bounds = window(row.fromUtc, row.toUtc, "rollup"); if (row.targetRevision !== undefined) bindRevision(row.targetRevision, expectedRevision); const nextCursor = cursor(row.nextCursor); if (row.hasMore !== (nextCursor !== null)) throw new Error("Invalid rollup pagination"); const snapshotUtc = row.snapshotUtc === undefined ? undefined : utc(row.snapshotUtc, "snapshotUtc")!; const sourceCutoffUtc = row.sourceCutoffUtc === undefined ? undefined : utc(row.sourceCutoffUtc, "sourceCutoffUtc")!; if (snapshotUtc && sourceCutoffUtc && Date.parse(snapshotUtc) < Date.parse(sourceCutoffUtc)) throw new Error("Invalid rollup snapshot"); const generation = row.generation === undefined ? undefined : integer(row.generation, "generation"); if (generation !== undefined && generation < 1) throw new Error("Invalid rollup generation");
  const items = row.items.map(item => { const x = object(item); keys(x, ["interval", "bucketStartUtc", "bucketEndUtc", "metricKey", "dimensionsSha256", "count", "min", "max", "sum", "mean", "last", "counterDelta", "ratePerSecond", "expected", "coverage", "resetCount", "gapCount", "truncated", "sourceCutoffUtc", "dimensions", "visibilityState", "catalogVersion", "algorithmVersion", "generation"], "rollup item"); required(x, ["bucketStartUtc", "bucketEndUtc", "metricKey", "count", "expected", "coverage", "truncated"], "rollup item"); const start = utc(x.bucketStartUtc, "bucketStartUtc")!; const end = utc(x.bucketEndUtc, "bucketEndUtc")!; const count = integer(x.count, "count"); const expected = integer(x.expected, "expected"); const coverage = number(x.coverage, "coverage"); if (Date.parse(end) <= Date.parse(start) || bounds && (Date.parse(start) < Date.parse(bounds[0]) || Date.parse(end) > Date.parse(bounds[1])) || x.metricKey !== metric || coverage < 0 || coverage > 1 || typeof x.truncated !== "boolean" || (expected === 0 ? coverage !== 0 : Math.abs(coverage - Math.min(1, count / expected)) > 1e-9) || !visibility.has(String(x.visibilityState ?? "complete"))) throw new Error("Invalid rollup item"); for (const key of ["min", "max", "sum", "mean", "last", "counterDelta", "ratePerSecond"]) if (x[key] !== null && x[key] !== undefined) number(x[key], key); if (x.generation !== undefined && (integer(x.generation, "generation") < 1)) throw new Error("Invalid rollup generation"); return { ...x, bucketStartUtc: start, bucketEndUtc: end, metricKey: x.metricKey as string, count, expected, coverage, truncated: x.truncated, sourceCutoffUtc: utc(x.sourceCutoffUtc, "sourceCutoffUtc", true), visibilityState: x.visibilityState ?? "complete" } as unknown as Rollup; });
  for (let i = 1; i < items.length; i++) if (Date.parse(items[i - 1]!.bucketStartUtc) > Date.parse(items[i]!.bucketStartUtc)) throw new Error("Rollups are out of order");
  return { targetId, metricKey: metric, items, hasMore: row.hasMore, nextCursor, state: row.state === undefined ? undefined : boundedState(row.state) as RollupPage["state"], snapshotUtc, sourceCutoffUtc, targetRevision: row.targetRevision as number | undefined, generation };
}
function validateSurfaceItem(surface: AnalyticsSurface, x: Record<string, unknown>, expectedRevision?: number): void {
  const revision = bindRevision(x.targetRevision, expectedRevision);
  switch (surface) {
    case "host/status": guid(x.hostId, "hostId"); text(x.hostName, "hostName", 512); if (!["pending", "active", "stale", "retired"].includes(String(x.bindingState)) || !["unknown", "available", "partial", "unsupported", "permission_denied"].includes(String(x.capabilityState))) throw new Error("Invalid host status"); integer(x.bindingRevision, "bindingRevision"); utc(x.observedAtUtc, "observedAtUtc"); break;
    case "host/metrics": utc(x.observedAtUtc, "observedAtUtc"); guid(x.runId, "runId"); catalogMetric(x.metricKey, "host metric"); number(x.value, "value"); dimensions(x.dimensions); break;
    case "replication/status": case "replication/evidence": utc(x.observedAtUtc, "observedAtUtc"); guid(x.runId, "runId"); if (typeof x.role !== "string" || x.role.length > 32 || typeof x.synchronizationState !== "string" || x.synchronizationState.length > 64) throw new Error("Invalid replication state"); if (x.sendQueueBytes !== null && x.sendQueueBytes !== undefined) integer(x.sendQueueBytes, "sendQueueBytes"); if (x.redoQueueBytes !== null && x.redoQueueBytes !== undefined) integer(x.redoQueueBytes, "redoQueueBytes"); if (![1, 2, 3].includes(Number(x.visibilityScope)) || !["complete", "local_summary", "visibility_gap"].includes(String(x.coverage)) || typeof x.stateAvailable !== "boolean") throw new Error("Invalid replication visibility"); if (x.visibilityGap !== null && x.visibilityGap !== undefined) { const gap = object(x.visibilityGap); keys(gap, ["kind", "reason", "identity"], "visibility gap"); if (gap.kind !== "visibility_gap" || gap.reason !== "distribution_database_unbound" || typeof gap.identity !== "string" || !/^[0-9a-f]{64}$/.test(gap.identity)) throw new Error("Invalid visibility gap"); } if (x.coverage === "visibility_gap" && x.visibilityGap === undefined) throw new Error("Missing visibility gap evidence"); break;
    case "diagnostics/search": utc(x.occurredAtUtc, "occurredAtUtc"); guid(x.eventId, "eventId"); text(x.eventKind, "eventKind", 64); integer(x.severity, "severity"); object(x.safeMetadata); utc(x.collectedAtUtc, "collectedAtUtc"); break;
    case "jobs": guid(x.jobId, "jobId"); if (!["rollup", "baseline", "forecast", "correlation", "backfill", "retention"].includes(String(x.jobKind)) || !["queued", "running", "succeeded", "partial", "failed", "cancelled"].includes(String(x.status))) throw new Error("Invalid analytics job"); utc(x.requestedAtUtc, "requestedAtUtc"); utc(x.startedAtUtc, "startedAtUtc", true); utc(x.completedAtUtc, "completedAtUtc", true); integer(x.attempt, "attempt"); break;
    case "incidents": guid(x.threadId, "threadId"); utc(x.openedAtUtc, "openedAtUtc"); utc(x.closedAtUtc, "closedAtUtc", true); integer(x.currentGeneration, "currentGeneration"); break;
    case "evidence-packets": utc(x.occurredAtUtc, "occurredAtUtc"); guid(x.packetId, "packetId"); text(x.evidenceKind, "evidenceKind", 64); guid(x.sourceRunId, "sourceRunId", true); if (typeof x.sourceDigest !== "string" || !/^[0-9a-f]{64}$/.test(x.sourceDigest)) throw new Error("Invalid source digest"); const confidence = number(x.confidence, "confidence"); if (confidence < 0 || confidence > 1 || !visibility.has(String(x.visibilityState))) throw new Error("Invalid evidence packet"); break;
    case "backfill": break;
  }
  void revision;
}
export function parseAnalyticsSurfacePage<T = Record<string, unknown>>(value: unknown, expectedSurface?: AnalyticsSurface, expectedTargetId?: string, expectedRevision?: number): AnalyticsSurfacePage<T> {
  const row = object(value); keys(row, ["targetId", "surface", "fromUtc", "toUtc", "items", "state", "nextCursor", "cutoffUtc", "snapshotUtc", "generation", "targetRevision"], "analytics surface"); required(row, ["targetId", "surface", "fromUtc", "toUtc", "items", "state", "nextCursor", "cutoffUtc", "snapshotUtc", "generation", "targetRevision"], "analytics surface");
  const targetId = bindTarget(row, expectedTargetId, expectedRevision); const surface = text(row.surface, "surface", 64) as AnalyticsSurface; if (!surfaces.has(surface)) throw new Error("Unsupported analytics surface"); if (expectedSurface && surface !== expectedSurface && !(expectedSurface === "backfill" && surface === "jobs")) throw new Error("Mismatched analytics surface");
  if (!Array.isArray(row.items) || row.items.length > 200) throw new Error("Invalid analytics page"); const state = boundedState(row.state); const nextCursor = cursor(row.nextCursor); const generation = integer(row.generation, "generation"); if (generation < 1) throw new Error("Invalid analytics generation"); const targetRevision = bindRevision(row.targetRevision, expectedRevision); const bounds = window(row.fromUtc, row.toUtc, "analytics"); if (!bounds) throw new Error("Analytics window is required"); const cutoffUtc = utc(row.cutoffUtc, "cutoffUtc")!; const snapshotUtc = utc(row.snapshotUtc, "snapshotUtc")!; if (Date.parse(snapshotUtc) < Date.parse(cutoffUtc)) throw new Error("Invalid analytics snapshot");
  const items = row.items.map(item => { const x = object(item); keys(x, surfaceKeys[surface], "analytics item"); required(x, surfaceKeys[surface], "analytics item"); validateSurfaceItem(surface, x, targetRevision); return x as T; });
  return { targetId, surface, items, state: state as AnalyticsSurfacePage<T>["state"], nextCursor, cutoffUtc, snapshotUtc, targetRevision, generation, fromUtc: bounds[0], toUtc: bounds[1] };
}
export function parseComparison(value: unknown, expectedTargetId?: string, expectedRevision?: number): AnalyticsComparison {
  const row = object(value); keys(row, ["targetId", "metricKey", "leftFromUtc", "leftToUtc", "rightFromUtc", "rightToUtc", "result", "targetRevision"], "comparison"); required(row, ["targetId", "metricKey", "leftFromUtc", "leftToUtc", "rightFromUtc", "rightToUtc", "result"], "comparison"); bindTarget(row, expectedTargetId, expectedRevision); if (row.targetRevision !== undefined) bindRevision(row.targetRevision, expectedRevision); catalogMetric(row.metricKey, "comparison metric"); const left = window(row.leftFromUtc, row.leftToUtc, "left"); const right = window(row.rightFromUtc, row.rightToUtc, "right"); if (!left || !right || Date.parse(left[1]) - Date.parse(left[0]) !== Date.parse(right[1]) - Date.parse(right[0])) throw new Error("Invalid comparison windows");
  const x = object(row.result); keys(x, ["leftValue", "rightValue", "delta", "percent", "leftSamples", "rightSamples", "complete"], "comparison result"); required(x, ["leftValue", "rightValue", "delta", "percent", "leftSamples", "rightSamples", "complete"], "comparison result"); for (const key of ["leftValue", "rightValue", "delta", "percent"]) if (x[key] !== null) number(x[key], key); if (typeof x.complete !== "boolean") throw new Error("Invalid comparison completeness"); return { leftValue: x.leftValue as number | null, rightValue: x.rightValue as number | null, delta: x.delta as number | null, percent: x.percent as number | null, leftSamples: integer(x.leftSamples, "leftSamples"), rightSamples: integer(x.rightSamples, "rightSamples"), complete: x.complete };
}
export function parseBaseline(value: unknown): Baseline {
  const x = object(value); keys(x, ["metricKey", "hourOfWeek", "completeDays", "sampleCount", "median", "mad", "p10", "p90", "coverage", "confidence", "windowStartUtc", "windowEndUtc", "generation", "visibilityState"], "baseline"); required(x, ["metricKey", "hourOfWeek", "completeDays", "sampleCount", "coverage", "confidence"], "baseline");
  const key = catalogMetric(x.metricKey, "baseline metric"); const hourOfWeek = integer(x.hourOfWeek, "hourOfWeek"); const completeDays = integer(x.completeDays, "completeDays"); const sampleCount = integer(x.sampleCount, "sampleCount"); if (hourOfWeek > 167) throw new Error("Invalid baseline metric");
  const optional = (name: string): number | null => x[name] == null ? null : number(x[name], name); const median = optional("median"), mad = optional("mad"), p10 = optional("p10"), p90 = optional("p90"); const coverage = number(x.coverage, "coverage"); const confidence = number(x.confidence, "confidence"); if (coverage < 0 || coverage > 1 || confidence < 0 || confidence > 1) throw new Error("Invalid baseline confidence");
  const windowStartUtc = x.windowStartUtc == null ? null : utc(x.windowStartUtc, "windowStartUtc")!; const windowEndUtc = x.windowEndUtc == null ? null : utc(x.windowEndUtc, "windowEndUtc")!; if (windowStartUtc && windowEndUtc && Date.parse(windowEndUtc) <= Date.parse(windowStartUtc)) throw new Error("Invalid baseline window"); const visibilityState = x.visibilityState === undefined ? undefined : text(x.visibilityState, "visibilityState", 16); if (visibilityState !== undefined && !visibility.has(visibilityState)) throw new Error("Invalid baseline visibility");
  return { metricKey: key, hourOfWeek, completeDays, sampleCount, median, mad, p10, p90, coverage, confidence, windowStartUtc, windowEndUtc, generation: x.generation === undefined ? undefined : integer(x.generation, "generation"), visibilityState: visibilityState as Baseline["visibilityState"] };
}
export function parseForecast(value: unknown): Forecast {
  const x = object(value); keys(x, ["metricKey", "horizonStartUtc", "horizonEndUtc", "estimate", "lowerBound", "upperBound", "slopePerDay", "confidence", "residual", "forecastId", "model", "sourceGeneration", "visibilityState"], "forecast"); required(x, ["metricKey", "horizonStartUtc", "horizonEndUtc", "confidence", "residual"], "forecast");
  const key = catalogMetric(x.metricKey, "forecast metric"); const horizonStartUtc = utc(x.horizonStartUtc, "horizonStartUtc")!, horizonEndUtc = utc(x.horizonEndUtc, "horizonEndUtc")!; if (Date.parse(horizonEndUtc) <= Date.parse(horizonStartUtc)) throw new Error("Invalid forecast window");
  const optional = (name: string): number | null => x[name] == null ? null : number(x[name], name); const confidence = number(x.confidence, "confidence"), residual = number(x.residual, "residual"); if (confidence < 0 || confidence > 1) throw new Error("Invalid forecast confidence"); const visibilityState = x.visibilityState === undefined ? undefined : text(x.visibilityState, "visibilityState", 16); if (visibilityState !== undefined && !visibility.has(visibilityState)) throw new Error("Invalid forecast visibility");
  return { metricKey: key, horizonStartUtc, horizonEndUtc, estimate: optional("estimate"), lowerBound: optional("lowerBound"), upperBound: optional("upperBound"), slopePerDay: optional("slopePerDay"), confidence, residual, forecastId: x.forecastId === undefined ? undefined : guid(x.forecastId, "forecastId", true), model: x.model === undefined ? "forecast-v1" : text(x.model, "model", 64), sourceGeneration: x.sourceGeneration === undefined ? 1 : integer(x.sourceGeneration, "sourceGeneration"), visibilityState: visibilityState as Forecast["visibilityState"] };
}
const retentionDataClasses = new Set(["m10_host_metrics", "m10_replication", "m10_rollups", "m10_evidence"]);
const retentionBlockReasons = new Set(["disabled", "duration_unconfigured", "recovery_attestation_missing", "reader_lease_active", "backfill_incomplete", "dependency_pending", "minimum_partition_floor", "utc_floor", "registry_missing", "lease_missing", "retention_disabled", "partition_not_attached", "within_retention_window"]);
function retentionDuration(value: unknown, enabled: boolean): string | null { if (value === null) { if (enabled) throw new Error("Enabled retention policy requires a duration"); return null; } if (!enabled) throw new Error("Disabled retention policy must not carry a duration"); if (typeof value !== "string" || !/^(?:\d{1,4}\.)?\d{2}:\d{2}:\d{2}(?:\.\d{1,7})?$/.test(value)) throw new Error("Invalid retention policy duration"); const match = /^(?:(\d{1,4})\.)?(\d{2}):(\d{2}):(\d{2})(?:\.(\d{1,7}))?$/.exec(value)!; const days = Number(match[1] ?? 0), hours = Number(match[2]), minutes = Number(match[3]), seconds = Number(match[4]); if (hours > 23 || minutes > 59 || seconds > 59 || days > 3650 || days * 86400 + hours * 3600 + minutes * 60 + seconds < 86400) throw new Error("Retention duration is outside its bounds"); return value; }
export function parseRetentionPolicy(value: unknown): RetentionPolicyResult { const row = object(value); keys(row, ["policy", "revision", "readAtUtc"], "retention policy"); const p = object(row.policy); keys(p, ["dataClass", "enabled", "retainFor", "minimumPartitionsToKeep"], "retention policy"); if (typeof p.dataClass !== "string" || !retentionDataClasses.has(p.dataClass) || typeof p.enabled !== "boolean") throw new Error("Invalid retention policy"); const floor = integer(p.minimumPartitionsToKeep, "minimumPartitionsToKeep"); if (floor < 1 || floor > 10000) throw new Error("Invalid retention policy floor"); retentionDuration(p.retainFor, p.enabled); const revision = integer(row.revision, "revision"); if (revision < 1) throw new Error("Invalid retention policy revision"); utc(row.readAtUtc, "readAtUtc"); return row as unknown as RetentionPolicyResult; }
export function parseRetentionPreview(value: unknown): RetentionPreview { const row = object(value); keys(row, ["entries", "truncated", "nextCursor", "evaluatedAtUtc"], "retention preview"); required(row, ["entries", "truncated", "nextCursor", "evaluatedAtUtc"], "retention preview"); if (!Array.isArray(row.entries) || row.entries.length > 1024 || typeof row.truncated !== "boolean") throw new Error("Invalid retention preview page"); const nextCursor = cursor(row.nextCursor); if (row.truncated !== (nextCursor !== null)) throw new Error("Invalid retention preview pagination"); utc(row.evaluatedAtUtc, "evaluatedAtUtc"); const identities = new Set<string>(); const entries = row.entries.map(item => { const x = object(item); keys(x, ["dataClass", "parentSchema", "parentTable", "partitionName", "rangeStartUtc", "rangeEndUtc", "eligible", "reason"], "retention preview entry"); required(x, ["dataClass", "parentSchema", "parentTable", "partitionName", "rangeStartUtc", "rangeEndUtc", "eligible", "reason"], "retention preview entry"); if (typeof x.dataClass !== "string" || !retentionDataClasses.has(x.dataClass) || typeof x.parentSchema !== "string" || !/^[A-Za-z0-9_.-]{1,128}$/.test(x.parentSchema) || typeof x.parentTable !== "string" || !/^[A-Za-z0-9_.-]{1,128}$/.test(x.parentTable) || typeof x.partitionName !== "string" || !/^[A-Za-z0-9_.-]{1,128}$/.test(x.partitionName) || typeof x.eligible !== "boolean" || typeof x.reason !== "string" || !retentionBlockReasons.has(x.reason) && x.reason !== "eligible") throw new Error("Invalid retention preview entry"); const start = utc(x.rangeStartUtc, "rangeStartUtc")!, end = utc(x.rangeEndUtc, "rangeEndUtc")!; if (Date.parse(end) <= Date.parse(start) || x.eligible !== (x.reason === "eligible")) throw new Error("Retention eligibility and reason disagree"); const identity = `${x.dataClass}\0${x.parentSchema}\0${x.parentTable}\0${x.partitionName}`; if (identities.has(identity)) throw new Error("Duplicate retention preview entry"); identities.add(identity); return { ...x, rangeStartUtc: start, rangeEndUtc: end } as RetentionPreview["entries"][number]; }); return { entries, truncated: row.truncated, nextCursor, evaluatedAtUtc: utc(row.evaluatedAtUtc, "evaluatedAtUtc")! }; }
export function parseBaselines(value: unknown, expectedTargetId?: string, expectedRevision?: number): readonly Baseline[] { const row = object(value); keys(row, ["targetId", "metricKey", "fromUtc", "toUtc", "items", "state", "targetRevision"], "baselines"); required(row, ["targetId", "metricKey", "fromUtc", "toUtc", "items", "state"], "baselines"); bindTarget(row, expectedTargetId, expectedRevision); if (row.targetRevision !== undefined) bindRevision(row.targetRevision, expectedRevision); catalogMetric(row.metricKey, "baselines metric"); if (!Array.isArray(row.items) || row.items.length > 200) throw new Error("Invalid baselines page"); window(row.fromUtc, row.toUtc, "baselines"); boundedState(row.state); return row.items.map(parseBaseline); }
export function parseForecasts(value: unknown, expectedTargetId?: string, expectedRevision?: number): readonly Forecast[] { const row = object(value); keys(row, ["targetId", "metricKey", "horizonDays", "items", "state", "targetRevision"], "forecasts"); required(row, ["targetId", "metricKey", "horizonDays", "items", "state"], "forecasts"); bindTarget(row, expectedTargetId, expectedRevision); if (row.targetRevision !== undefined) bindRevision(row.targetRevision, expectedRevision); catalogMetric(row.metricKey, "forecasts metric"); if (typeof row.horizonDays !== "number" || !Number.isSafeInteger(row.horizonDays) || row.horizonDays < 1 || row.horizonDays > 366 || !Array.isArray(row.items) || row.items.length > 200) throw new Error("Invalid forecasts page"); boundedState(row.state); return row.items.map(parseForecast); }

export function parseMutationReceipt(value: unknown): import("./analyticsTypes").AnalyticsMutationReceipt {
  const row = object(value); keys(row, ["operationId", "state", "revision", "acceptedAtUtc"], "mutation receipt"); required(row, ["operationId", "state", "revision", "acceptedAtUtc"], "mutation receipt");
  const operationId = guid(row.operationId, "operationId")!; const state = text(row.state, "state", 32); if (!["queued", "committed", "replayed", "accepted", "blocked", "detached", "grace", "dropped", "failed", "retry"].includes(state)) throw new Error("Invalid mutation state");
  const revision = row.revision === null ? null : integer(row.revision, "revision"); if (revision !== null && revision < 1) throw new Error("Invalid mutation revision"); const acceptedAtUtc = utc(row.acceptedAtUtc, "acceptedAtUtc")!;
  return { operationId, state, revision, acceptedAtUtc };
}
export function parseRetentionExecution(value: unknown): import("./analyticsTypes").RetentionExecutionResult {
  const row = object(value); keys(row, ["executionId", "state", "blockReason", "dropAfterUtc", "failureCode"], "retention execution"); required(row, ["executionId", "state", "blockReason", "dropAfterUtc", "failureCode"], "retention execution");
  const executionId = guid(row.executionId, "executionId")!; const state = integer(row.state, "state"); if (state < 1 || state > 7) throw new Error("Invalid retention execution state"); const blockReason = row.blockReason === null ? null : integer(row.blockReason, "blockReason"); if (blockReason !== null && (blockReason < 1 || blockReason > 10)) throw new Error("Invalid retention block reason"); const dropAfterUtc = row.dropAfterUtc === null ? null : utc(row.dropAfterUtc, "dropAfterUtc")!; const failureCode = row.failureCode === null ? null : text(row.failureCode, "failureCode", 256); return { executionId, state, blockReason, dropAfterUtc, failureCode };
}
