<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>SqlObserver.Security</RootNamespace>
    <AssemblyName>SqlObserver.Security</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../SqlObserver.Application/SqlObserver.Application.csproj" />
    <ProjectReference Include="../SqlObserver.Domain/SqlObserver.Domain.csproj" />
  </ItemGroup>
</Project>
